<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="How to use Ansible variables, Using Ansible variables, overidding ansible variables, ansible role hiereachy">
    <meta name="keywords" content="How to use Ansible variables, Using Ansible variables, overidding ansible variables, ansible role hiereachy">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>How to use Ansible variables, Using Ansible variables, overidding ansible variables, ansible role hiereachy</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/ansible-roles.jsp"
  },
  "name" : "How to use Ansible variables, Using Ansible variables, overidding ansible variables, ansible role hiereachy",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "How to use Ansible variables, Using Ansible variables, overidding ansible variables, ansible role hiereachy",
  "image":"https://8gwifi.org/docs/img/ansible-roles.png",
  "datePublished" : "2018-07-03",
  "dateModified": "2018-07-03",
  "articleSection" : "Ansible variable property Hierarchy , Running the playbook, Overriding Ansible variable Property, Override group var through Host Variable ",
  "articleBody" : [ "How to use Ansible Variable, Overriding Ansible variables"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">How to use Ansible Variable, Overriding Ansible variables</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on Tuesday July 3rd</p>


        
          <!-- Preview Image 
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
          -->
           <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>

          <hr>

          <!-- Post Content -->
          <h2 class="mt-4">Ansible Variable, Overriding Ansible variables, Group Vars/ Host Variables</h2>

          <p>Ansible supports property hierarchy, the ansible variable can be overwritten if the following condition matches</strong> </p>
          <p>Ansible <strong>Order of Execution is</strong></p>
          <p>
          <ul>
          <li>If variables present in <strong>roles/roletest/tasks/main.yml</strong> exists,then tasks listed therein will be added to the play</li>
          <li>If variables present in <strong>roles/roletest/handlers/main.yml</strong> exists,then handlers listed therein will be added to the play</li>
          <li>If variables present in <strong>roles/roletest/vars/main.yml</strong> exists,then variables listed therein will be added to the play</li>
          <li>If variables present in <strong>roles/roletest/defaults/main.yml</strong> exists,then variables listed therein will be added to the play</li>
          <li>If variables present in <strong>roles/roletest/meta/main.yml</strong> exists,any role dependencies listed therein will be added to the list of roles</li>
          </ul>
          </p>
		  <img class="img-fluid rounded" src="img/ansible-roles.png" alt="">
		  <hr>
		  <h3 class="mt-4">Lets Begin the Test </h3>
		  <p><strong>In the first create the directory structure used in this example</strong></p>
		  <pre><code class="html">mkdir -p roles/roletest/tasks/
mkdir -p roles/roletest/vars/
mkdir -p roles/roletest/handlers/
mkdir -p roles/roletest/defaults/
mkdir -p group_vars/</code></pre>	  

    	  <hr>
		  <p>To begin this test,define an ansible variable <strong>first</strong> in the <strong>roletest/defaults/main.yml</strong> and in the <strong>roletest/vars/main.yml</strong></p>
		  <p>Content of these files are</p>

		  <pre><code class="html">[ansible@controller roles]$ cat roletest/defaults/main.yml 
first: coming default main
[ansible@controller roles]$ cat roletest/vars/main.yml 
first: 'coming from vars main'
[ansible@controller roles]$ </code></pre>

		  <p>The <strong>tasks/main.yml</strong> file, a very basic definition with <strong>debug</strong> tasks to check from where the ansible variable first is coming</p>
		  <pre><code class="html">[ansible@controller roles]$ cat roletest/tasks/main.yml 
---
  - debug:
      msg: "{{first}}"</code></pre>
      
          <p>The content of the  <strong>roletest.yml</strong>  Playbook run file</p>
		  <pre><code class="html">[ansible@controller opt]$ cat roletest.yml 
- hosts: localhost
  roles:
     - { role: roletest }</code></pre>
     		<p><strong>Running the playbook, I</strong></p>
     		<p>In the first example the ansible variable <strong>first</strong> is loaded from the  <strong>roletest/vars/main.yml </strong> file, since the  <strong>tasks/main.yml</strong> doesn't contain this variable defination</p>
		 <pre><code class="html">[ansible@controller opt]$ ansible-playbook roletest.yml 
TASK [roletest : debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "coming from vars main"
}</code></pre>

<p>Now remove this variable first from the <strong>roletest/vars/main.yml</strong> file and re-run the playbook</p>
<p>This time variable is picked from <strong>roletest/defualt/main.yml</strong></p>
<pre><code class="html">
TASK [roletest : debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "coming default main"
}</code></pre>
		  
		  <hr>

		  <h3 class="mt-4">Overriding Ansible variable Property</h3>
          <p>With this structure using <strong> group variable the property can be overridden </strong> </p>
         
			 <p>create variable first in the <strong>group_vars/all.yml</strong>and re-run the Playbook (Group Variable)</p>
<pre><code class="html">[ansible@controller opt]$ cat group_vars/all.yml 
first: "Inside groupvar"</code></pre>

<p>On the Playbook run this property is overridden by group variable</strong></p>

<pre><code class="html">TASK [roletest : debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "coming from groupvar"
}</code></pre>

<p><strong>Override group var through Host Variable </strong></p>
<p> Update the Inventory file and define <strong>host variable</strong></p>
<pre><code class="html">[local]
localhost first="Coming from Inventroy"</code></pre>
	 
	 <p>Run the Ansible Playbook you will be notice inventory property is given with <strong>max priority</strong> from group variable</p>
	 <pre><code class="html">TASK [roletest : debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "Coming from the Inventory"
}</code></pre>
<hr>
<h4 class="mt-4">Passing Variable in Ansible Playbook Run </h4>
<p>In this example we will be passing the first variable in the Ansible main playbook run file <strong>roletest.yml</strong></p>
<p>Note <font color="red">We have still not defined any variable defination in the tasks/main.yml file</font></p>
<pre><code class="html">[ansible@controller opt]$ cat roletest.yml 
- hosts: localhost
  vars:
     - first: "Coming from Main run"
  roles:
     - { role: roletest }</code></pre>
<p>After running the Playbook, this ansible variable <strong>first</strong> has picked up the Max priority</p>
<pre><code class="html">
TASK [roletest : debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "Coming from Main run"
}</code></pre>
<p>Final test </p>
<p>Test ansible variable <strong>first</strong> placed in <strong>tasks/main.yml</strong> will have the MAX preferences
</p> 
<p>Now this ansible variable <strong>first</strong> is defined in <strong>HOST_VARIABLE</strong> , <strong>GROUP_VARS</strong>, <strong>defaults</strong> and <strong>vars</strong></p>

<p>Modifying the file <strong>tasks/main.yml</strong> and including the variable file <strong>myvar.yml</strong></p>
<pre><code class="html">[ansible@controller opt]$ cat roles/roletest/tasks/main.yml 
---
  - include_vars: myvar.yml
  - debug:
      msg: "{{first}}"</code></pre>

<p>Place this file myvar.yml under <strong>roletest/vars/</strong> and run the playbook</p>

<p>The sample Content of the file</p>
<pre><code class="html">[ansible@controller opt]$ cat roles/roletest/vars/myvar.yml 
first: 'THIS ALWAYS GIVE FIRST PRIORITY'</code></pre>

<p> The Ansible Playbook run output </p>
<pre><code class="html">TASK [roletest : debug] *****************************************************************************************
ok: [localhost] => {
    "msg": "THIS ALWAYS GIVE FIRST PRIORITY"
}</code></pre>

<hr>

<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         <%@ include file="related-linux.jsp"%>
         
         <%@ include file="related-openstack.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>