<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Linux http,curl,wget examples form post authentication,tls client, form download">
<meta name="keywords"content="Linux http,curl,wget examples form post authentication and others">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>http, curl and wget examples</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/curl.jsp"
  },
  "name" : "Linux http,curl,wget examples form post authentication,tls client, form download",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Linux http,curl,wget examples form post authentication,tls client, form download",
  "image":"https://8gwifi.org/docs/img/httpmethod.png",
  "datePublished" : "2019-10-01",
  "dateModified": "2019-10-01",
  "articleSection" : "Lets Visit Linux Mount and Unmount Again",
  "articleBody" : [ "Fetch the headers only","Linux Device type", "HTTP Methods ", "curl HTTP POST With content-type application/x-www-form-urlencoded", "wget HTTP POST with application/json", "curl basic auth", "curl Authorization Bearer", "curl Digest auth" , "curl Download File", "curl follow redirect"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">HTTPIE CURL and WGET</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Tuesday October 1st 2019</p>

				<hr>



				<img class="img-fluid rounded" src="img/httpmethod.png" alt="Referefce 8gwifi.org">

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>
					<p class="has-line-data" data-line-start="2" data-line-end="3">Utilities are essentials for working with HTTP methods many such utilities exist which eases our daily Job. In this tutorial we will go to some of the practical use-case of handling HTTP methods which can be used in our daily life to increase our productivity and cover the below utilities</p>
<ul>
<li class="has-line-data" data-line-start="4" data-line-end="5"><strong>httpie</strong>: Client-side implementation of the HTTP/1.1 protocol</li>
<li class="has-line-data" data-line-start="5" data-line-end="6"><strong>curl</strong>: transfer a URL</li>
<li class="has-line-data" data-line-start="6" data-line-end="8"><strong>wget</strong> : The non-interactive network downloader</li>
</ul>
<p class="has-line-data" data-line-start="8" data-line-end="9">For Docker user can pull the Image</p>
<pre><code class="html">docker pull anishnath/httpclient
</code></pre>
<h2 class="code-line" data-line-start=13 data-line-end=14 ><a id="Fetch_the_headers_only_13"></a>Fetch the headers only</h2>
<ul>
<li class="has-line-data" data-line-start="15" data-line-end="16">http</li>
</ul>
<pre><code class="html"># http 8gwifi.org
HTTP/1.1 301 Moved Permanently
CF-RAY: 51ec3d603adbce2b-LHR
.......
.......
Vary: Accept-Encoding
</code></pre>
<ul>
<li class="has-line-data" data-line-start="25" data-line-end="26">curl</li>
</ul>
<pre><code class="html"># curl -I 8gwifi.org
/httpclient # curl -I 8gwifi.org
HTTP/1.1 301 Moved Permanently
........
........
Connection: keep-alive
</code></pre>
<h2 class="code-line" data-line-start=36 data-line-end=37 ><a id="HTTP_Methods_36"></a>HTTP Methods</h2>
<h3 class="code-line" data-line-start=38 data-line-end=39 ><a id="POST_38"></a>POST</h3>
<p class="has-line-data" data-line-start="40" data-line-end="41">HTTP POST With <strong>content-type: application/x-www-form-urlencoded</strong></p>
<pre><code class="html">curl -X POST \
  https://8gwifi.org/crypto/rest/encryptdecrypt/encrypt \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'p_msg=Hello%208gwifi.org&amp;p_secretkey=a23c6e1a4aa987e766ecad497f2f4166fb4117b64adfb8bc&amp;p_cipher=AES_128%2FCFB%2FNOPADDING'
</code></pre>
<pre><code class="html">http --form POST https://8gwifi.org/crypto/rest/encryptdecrypt/encrypt \
  content-type:application/x-www-form-urlencoded \
  p_msg='Hello 8gwifi.org' \
  p_secretkey=a23c6e1a4aa987e766ecad497f2f4166fb4117b64adfb8bc \
  p_cipher=AES_128/CFB/NOPADDING
</code></pre>
<pre><code class="html">wget --quiet \
  --method POST \
  --header 'content-type: application/x-www-form-urlencoded' \
  --body-data 'p_msg=Hello%208gwifi.org&amp;p_secretkey=a23c6e1a4aa987e766ecad497f2f4166fb4117b64adfb8bc&amp;p_cipher=AES_128%2FCFB%2FNOPADDING' \
  --output-document \
  - https://8gwifi.org/crypto/rest/encryptdecrypt/encrypt
</code></pre>
<p class="has-line-data" data-line-start="65" data-line-end="66"><strong>HTTP POST with multipart/form-data</strong></p>
<ul>
<li class="has-line-data" data-line-start="67" data-line-end="68">curl</li>
</ul>
<pre><code class="html">curl --request POST \
  --url https://0cloud0.com/ \
  --header 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  --form hello=21
</code></pre>
<ul>
<li class="has-line-data" data-line-start="75" data-line-end="76">http</li>
</ul>
<pre><code class="html">echo '------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=&quot;hello&quot;

21
------WebKitFormBoundary7MA4YWxkTrZu0gW--' |  \
  http POST https://8gwifi.org/crypto/rest/encryptdecrypt/encrypt \
  content-type:'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
</code></pre>
<ul>
<li class="has-line-data" data-line-start="86" data-line-end="87">wget</li>
</ul>
<pre><code class="html">wget --quiet \
  --method POST \
  --header 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  --body-data '------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=&quot;hello&quot;\r\n\r\n21\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--' \
  --output-document \
  - https://0cloud0.com/ 
</code></pre>
<p class="has-line-data" data-line-start="96" data-line-end="97"><strong>HTTP POST with application/json</strong></p>
<ul>
<li class="has-line-data" data-line-start="98" data-line-end="99">http</li>
</ul>
<pre><code class="html">echo '{
  &quot;id&quot;: 1,
  &quot;name&quot;: &quot;JSON DEMO&quot;
}' |  \
  http POST https://example.com \
  content-type:application/json
</code></pre>
<ul>
<li class="has-line-data" data-line-start="108" data-line-end="109">curl</li>
</ul>
<pre><code class="html">curl --request POST \
  --url https://example.com \
  --header 'content-type: application/json' \
  --data '{\n  &quot;id&quot;: 1,\n  &quot;name&quot;: &quot;JSON DEMO&quot;\n}'
</code></pre>
<ul>
<li class="has-line-data" data-line-start="116" data-line-end="117">wget</li>
</ul>
<pre><code class="html">wget --quiet \
  --method POST \
  --header 'content-type: application/json' \
  --body-data '{\n  &quot;id&quot;: 1,\n  &quot;name&quot;: &quot;JSON DEMO&quot;\n}' \
  --output-document \
  - https://example.com
</code></pre>
<p class="has-line-data" data-line-start="126" data-line-end="127"><strong>HTTP POST with application/xml</strong></p>
<ul>
<li class="has-line-data" data-line-start="128" data-line-end="129">wget</li>
</ul>
<pre><code class="html">wget --quiet \
  --method POST \
  --header 'content-type: application/xml' \
  --body-data '&lt;xml&gt;\n  &lt;heading&gt;XML Demo&lt;/heading&gt;\n&lt;/xml&gt;' \
  --output-document \
  - https://example.com
</code></pre>
<ul>
<li class="has-line-data" data-line-start="138" data-line-end="139">http</li>
</ul>
<pre><code class="html">  echo '&lt;xml&gt;
  &lt;heading&gt;XML Demo&lt;/heading&gt;
&lt;/xml&gt;' |  \
  http POST https://example.com \
  content-type:application/xml 
</code></pre>
<ul>
<li class="has-line-data" data-line-start="147" data-line-end="149">curl</li>
</ul>
<pre><code class="html"> curl --request POST \
  --url https://example.com \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/xml' \
  --data '&lt;xml&gt;\n  &lt;heading&gt;XML Demo&lt;/heading&gt;\n&lt;/xml&gt;'
</code></pre>
<h3 class="code-line" data-line-start=158 data-line-end=159 ><a id="PATCH_158"></a>PATCH</h3>
<p class="has-line-data" data-line-start="160" data-line-end="161">A HTTP patch operation with required headers</p>
<ul>
<li class="has-line-data" data-line-start="162" data-line-end="163">http</li>
</ul>
<pre><code class="html">http PATCH https://api.cloudflare.com/client/v4 \
  x-auth-email:anish2good@yahoo.co.in \
  x-auth-key:1b2c4be9f9432d53e0cfbc61439de679
</code></pre>
<ul>
<li class="has-line-data" data-line-start="168" data-line-end="169">curl</li>
</ul>
<pre><code class="html">curl --request PATCH \
  --url https://api.cloudflare.com/client/v4 \
  --header 'x-auth-email: anish2good@yahoo.co.in' \
  --header 'x-auth-key: 1b2c4be9f9432d53e0cfbc61439de679'
</code></pre>
<ul>
<li class="has-line-data" data-line-start="175" data-line-end="176">wget</li>
</ul>
<pre><code class="html">wget --quiet \
  --method PATCH \
  --header 'x-auth-email: email_id' \
  --header 'x-auth-key: 1b2c4be9f9432d53e0cfbc61439de679' \
  --output-document \
  - https://api.cloudflare.com/client/v4
</code></pre>
<h2 class="code-line" data-line-start=185 data-line-end=186 ><a id="Authentication_185"></a>Authentication</h2>
<ul>
<li class="has-line-data" data-line-start="187" data-line-end="188"><strong>Basic auth</strong></li>
</ul>
<pre><code class="html">http -a username:password http://8gwifi.org
</code></pre>
<p class="has-line-data" data-line-start="191" data-line-end="192"><strong>curl</strong></p>
<pre><code class="html">curl -u username:password http://8gwifi.org
curl --header &quot;Authorization: Basic $AUTH&quot; http://8gwifi.org
</code></pre>
<p class="has-line-data" data-line-start="196" data-line-end="197"><strong>wget</strong></p>
<pre><code class="html">wget  \
  --method GET \
  --header 'authorization: Basic YW5pc2g6YW5pc2g=' \
  - https://0cloud0.com/
</code></pre>
<ul>
<li class="has-line-data" data-line-start="204" data-line-end="206"><strong>Authorization Bearer</strong></li>
</ul>
<pre><code class="html">curl --header &quot;Authorization: Bearer $TOKEN&quot; http://8gwifi.org
</code></pre>
<ul>
<li class="has-line-data" data-line-start="210" data-line-end="211"><strong>Digest auth</strong></li>
</ul>
<pre><code class="html">http -A digest -a username:password https://0cloud0.com
curl --digest --user username:password https://0cloud0.com
</code></pre>
<ul>
<li class="has-line-data" data-line-start="215" data-line-end="216"><strong>NTLM</strong></li>
</ul>
<pre><code class="html">curl --ntlm --user username:password https://0cloud0.com
</code></pre>
<ul>
<li class="has-line-data" data-line-start="220" data-line-end="221"><strong>Negotiate</strong></li>
</ul>
<pre><code class="html">curl --negotiate --user username:password https://0cloud0.com
</code></pre>
<ul>
<li class="has-line-data" data-line-start="225" data-line-end="228"><strong>Password prompt</strong><br>
<code>http -a username https://0cloud0.com</code></li>
</ul>
<h2 class="code-line" data-line-start=228 data-line-end=229 ><a id="TLS_Handling_228"></a>TLS Handling</h2>
<p class="has-line-data" data-line-start="230" data-line-end="231"><strong>Allow Insecure connection</strong></p>
<pre><code class="html">curl  -k https://example.com
</code></pre>
<p class="has-line-data" data-line-start="235" data-line-end="236"><strong>Client certificate Validation</strong></p>
<pre><code class="html">curl  -E  wk.cert  https://example.com
</code></pre>
<p class="has-line-data" data-line-start="241" data-line-end="242"><strong>Use Specfic TLS version to Connect</strong></p>
<pre><code class="html"># curl  -I --tlsv1.3 https://msn.com
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to msn.com:443 
</code></pre>
<pre><code class="html"># curl  -I --tlsv1.2 https://msn.com
HTTP/1.1 301 Moved Permanently
Content-Length: 143
Content-Type: text/html; charset=UTF-8
Location: https://www.msn.com/
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Tue, 01 Oct 2019 10:39:40 GMT
</code></pre>
<pre><code class="html">http --ssl tls1.2  https://msn.com
</code></pre>
<h2 class="code-line" data-line-start=263 data-line-end=264 ><a id="Download_File_263"></a>Download File</h2>
<ul>
<li class="has-line-data" data-line-start="265" data-line-end="266">http</li>
</ul>
<pre><code class="html"># http --download  https://8gwifi.org/docs/img/6book.png

Downloading 167.86 kB to &quot;6book.png&quot;
Done. 167.86 kB in 0.39169s (428.57 kB/s)
</code></pre>
<ul>
<li class="has-line-data" data-line-start="273" data-line-end="274">curl</li>
</ul>
<pre><code class="html"># curl https://8gwifi.org/docs/img/6book.png --output myfile.png
% Total  % Received % Xferd  Average Speed Time  Time Time  Current
Dload  Upload Total Spent  Left  Speed
100  167k  100  167k  0 0 168k  0 --:--:-- --:--:-- --:--:--  167k
</code></pre>
<ul>
<li class="has-line-data" data-line-start="281" data-line-end="283">wget</li>
</ul>
<pre><code class="has-line-data" data-line-start="284" data-line-end="286">wget https://8gwifi.org/docs/img/6book.png
</code></pre>
<p class="has-line-data" data-line-start="288" data-line-end="289"><strong>Silent Download</strong></p>
<pre><code class="html">curl https://8gwifi.org/docs/img/6book.png --output myfile.png -s
</code></pre>
<h2 class="code-line" data-line-start=294 data-line-end=295 ><a id="Follow_30x_Location_redirects_294"></a>Follow 30x Location redirects</h2>
<ul>
<li class="has-line-data" data-line-start="296" data-line-end="297">curl</li>
</ul>
<pre><code class="html"># curl -L -I http://8gwifi.org

HTTP/1.1 301 Moved Permanently
........
........
Connection: keep-alive

HTTP/2 200 
............
.............
cf-ray: 51ed29d20f79bb94-LHR
</code></pre>

<p>If you have any more Idea Please paste on comments I will add this on the List with your Name</p>
				<p>
					Next Reading : <a href="linux-monitor-commands.jsp">How to
						Monitoring All Executed Commands in Linux </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>