<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="How to create docker base image for cents7,debian,ubuntu,redhat,alpine">
<meta name="keywords"content="How to create docker base image for cents7,debian,ubuntu,redhat,alpine, docker interview questions">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>How to create docker base image for cents7,debian,ubuntu,redhat,alpine</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/docker-baseimage.jsp"
  },
  "name" : "How to create docker base image for cents7,debian,ubuntu,redhat,alpine",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "How to create docker base image for cents7,debian,ubuntu,redhat,alpine",
  "image":"https://8gwifi.org/docs/img/baseimage.png",
  "datePublished" : "2019-09-30",
  "dateModified": "2019-09-30",
  "articleSection" : "How to create docker base image",
  "articleBody" : [ "How to create docker base image","FROM scratch", "The Dockerfile of creating Centos7 base Image", "The Dockerfile of creating debian base Image"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">Creating Docker Base Images</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Monday September 30th 2019</p>

				<hr>



				<img class="img-fluid rounded" src="img/baseimage.png"alt="Referefce 8gwifi.org"> 

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>
					<p class="has-line-data" data-line-start="2" data-line-end="3"><strong>FROM scratch</strong> : The scratch image is mostly used for building base images, this image is the most minimal image in Docker doesn't contain any folders/files.</p>
<p class="has-line-data" data-line-start="4" data-line-end="5">Here is the example of creating sample base images for your environment.</p>
<h2 class="code-line" data-line-start=6 data-line-end=7 ><a id="Centos7_6"></a>Centos7</h2>
<p class="has-line-data" data-line-start="8" data-line-end="9">The <strong>Dockerfile</strong> of creating Centos7 base Image. The <a href="https://github.com/CentOS/sig-cloud-instance-images/raw/CentOS-7.2.1511/docker/centos-7.2.1511-docker.tar.xz">centos-7.2.1511-docker.tar.xz</a> contains all the files system files for Centos7.</p>
<pre><code class="language-console">FROM scratch
LABEL org.label-schema.schema-version=&quot;1.0&quot; \
    org.label-schema.name=&quot;CentOS Base Image&quot; \
    maintainer=&quot;https://0cloud0.com&quot; \
    org.label-schema.vcs-description=&quot;centos7 Base Image-minimal&quot; \
    org.label-schema.docker.cmd=&quot;docker run centos7&quot; \
    org.label-schema.vendor=&quot;CentOS&quot; \
    org.label-schema.license=&quot;GPLv2&quot; \
    org.label-schema.build-date=&quot;20190801&quot;
ADD centos-7.2.1511-docker.tar.xz /
CMD [&quot;/bin/bash&quot;]
</code></pre>
<p class="has-line-data" data-line-start="24" data-line-end="25">Build the Image</p>
<pre><code class="language-console">$ docker build -t centos7base .
Sending build context to Docker daemon  41.64MB
Step 1/4 : FROM scratch
 ---&gt; 
Step 2/4 : LABEL org.label-schema.schema-version &quot;1.0&quot; org.label-schema.name &quot;CentOS Base Image&quot; maintainer &quot;https://0cloud0.com&quot; org.label-schema.vcs-description &quot;centos7 Base Image-minimal&quot; org.label-schema.docker.cmd &quot;docker run centos7&quot; org.label-schema.vendor &quot;CentOS&quot; org.label-schema.license &quot;GPLv2&quot; org.label-schema.build-date &quot;20190801&quot;
 ---&gt; Running in ba49592c00d7
 ---&gt; b41063db123d
Removing intermediate container ba49592c00d7
Step 3/4 : ADD centos-7.2.1511-docker.tar.xz /
 ---&gt; e37168ffbf32
Step 4/4 : CMD /bin/bash
 ---&gt; Running in 6a717baa623a
 ---&gt; 381e5df2768e
Removing intermediate container 6a717baa623a
Successfully built 381e5df2768e
Successfully tagged centos7base:latest
</code></pre>
<p class="has-line-data" data-line-start="45" data-line-end="46">Run the Image and open the Interactive Terminal</p>
<pre><code class="language-console">$ docker run -it centos7base sh
sh-4.2# 
</code></pre>
<p class="has-line-data" data-line-start="52" data-line-end="53">Check the Centos7 Base release version.</p>
<pre><code class="language-console">sh-4.2# cat /etc/os-release 
NAME=&quot;CentOS Linux&quot;
VERSION=&quot;7 (Core)&quot;
ID=&quot;centos&quot;
ID_LIKE=&quot;rhel fedora&quot;
VERSION_ID=&quot;7&quot;
PRETTY_NAME=&quot;CentOS Linux 7 (Core)&quot;
ANSI_COLOR=&quot;0;31&quot;
CPE_NAME=&quot;cpe:/o:centos:centos:7&quot;
HOME_URL=&quot;https://www.centos.org/&quot;
BUG_REPORT_URL=&quot;https://bugs.centos.org/&quot;

CENTOS_MANTISBT_PROJECT=&quot;CentOS-7&quot;
CENTOS_MANTISBT_PROJECT_VERSION=&quot;7&quot;
REDHAT_SUPPORT_PRODUCT=&quot;centos&quot;
REDHAT_SUPPORT_PRODUCT_VERSION=&quot;7&quot;
</code></pre>

<p><h2>Video Demo </h2> </p>
<iframe width="420" height="315"
src="https://youtube.com/embed/sOo99FSNXmw">
</iframe>

<hr>

<h2 class="code-line" data-line-start=73 data-line-end=74 ><a id="Debian_73"></a>Debian</h2>
<p class="has-line-data" data-line-start="75" data-line-end="76">The <code>Dockerfile</code> of creating Debian 10 base Image. The <a href="https://github.com/debuerreotype/docker-debian-artifacts/blob/de09dd55b6328b37b89a33e76b698f9dbe611fab/buster/slim/rootfs.tar.xz">rootfs.tar.xz</a> contains all the files system files for Debian 10.</p>
<pre><code class="language-console">FROM scratch
LABEL org.label-schema.schema-version=&quot;1.0&quot; \
    org.label-schema.name=&quot;Debian Base Image&quot; \
    maintainer=&quot;https://0cloud0.com Anish Nath&quot; \
    org.label-schema.vcs-description=&quot;Debian 10 Base Image-minimal&quot; \
    org.label-schema.docker.cmd=&quot;docker run -it debian sh&quot; \
    org.label-schema.vendor=&quot;Debian&quot; \
    org.label-schema.license=&quot;GPLv2&quot; \
    org.label-schema.build-date=&quot;20190801&quot;
ADD rootfs.tar.xz /
CMD [&quot;/bin/bash&quot;]
</code></pre>
<p class="has-line-data" data-line-start="91" data-line-end="92">Build the Image</p>
<pre><code class="language-console">$ docker build -t debianbase .
Sending build context to Docker daemon  70.14kB
Step 1/4 : FROM scratch
 ---&gt; 
Step 2/4 : LABEL org.label-schema.schema-version &quot;1.0&quot; org.label-schema.name &quot;Debian Base Image&quot; maintainer &quot;https://0cloud0.com Anish Nath&quot; org.label-schema.vcs-description &quot;centos7 Base Image-minimal&quot; org.label-schema.docker.cmd &quot;docker run -it debian sh&quot; org.label-schema.vendor &quot;Debian&quot; org.label-schema.license &quot;GPLv2&quot; org.label-schema.build-date &quot;20190801&quot;
 ---&gt; Running in b26251a26114
 ---&gt; 56ab96d932a9
Removing intermediate container b26251a26114
Step 3/4 : ADD rootfs.tar.xz /
 ---&gt; 64fa174d654d
Step 4/4 : CMD /bin/bash
 ---&gt; Running in 87a6abd6b93a
 ---&gt; 9233dd6b47b6
Removing intermediate container 87a6abd6b93a
Successfully built 9233dd6b47b6
Successfully tagged debianbase:latest
</code></pre>
<p class="has-line-data" data-line-start="113" data-line-end="114">Run the Image and open the Interactive Terminal</p>
<pre><code class="language-console">$ docker run -it debian sh 
# cat /etc/os-release
PRETTY_NAME=&quot;Debian GNU/Linux 10 (buster)&quot;
NAME=&quot;Debian GNU/Linux&quot;
VERSION_ID=&quot;10&quot;
VERSION=&quot;10 (buster)&quot;
VERSION_CODENAME=buster
ID=debian
HOME_URL=&quot;https://www.debian.org/&quot;
SUPPORT_URL=&quot;https://www.debian.org/support&quot;
BUG_REPORT_URL=&quot;https://bugs.debian.org/&quot;
</code></pre>

<p><h2>Video Demo </h2> </p>
<iframe width="420" height="315"
src="https://youtube.com/embed/jip0YTNtXzA">
</iframe>

<hr>

<h2 class="code-line" data-line-start=130 data-line-end=131 ><a id="Ubuntu_1904_130"></a>Ubuntu 19.04</h2>
<p class="has-line-data" data-line-start="132" data-line-end="133">The <code>Dockerfile</code> of creating Ubuntu19.04 base Image. The <a href="http://cdimage.ubuntu.com/ubuntu-base/releases/19.04/release/ubuntu-base-19.04-base-amd64.tar.gz">ubuntu-base-19.04-base-amd64.tar.gz</a> contains all the files system files for Ubuntu19.04.</p>
<pre><code class="language-console">FROM scratch
LABEL org.label-schema.schema-version=&quot;1.0&quot; \
    org.label-schema.name=&quot;Ubuntu Base Image&quot; \
    maintainer=&quot;https://0cloud0.com Anish Nath&quot; \
    org.label-schema.vcs-description=&quot;ubuntu Base Image-minimal&quot; \
    org.label-schema.docker.cmd=&quot;docker run -it ubuntu sh&quot; \
    org.label-schema.vendor=&quot;ubuntu&quot; \
    org.label-schema.license=&quot;GPLv2&quot; \
    org.label-schema.build-date=&quot;20190801&quot;
ADD ubuntu-base-19.04-base-amd64.tar.gz /
CMD [&quot;/bin/bash&quot;]
</code></pre>
<p class="has-line-data" data-line-start="148" data-line-end="149">Build the Image</p>
<pre><code class="language-console">$ docker build -t ubuntu19.04base .
Sending build context to Docker daemon  28.99MB
Step 1/4 : FROM scratch
 ---&gt; 
Step 2/4 : LABEL org.label-schema.schema-version &quot;1.0&quot; org.label-schema.name &quot;Ubuntu Base Image&quot; maintainer &quot;https://leanpub.com/dockerfile Anish Nath&quot; org.label-schema.vcs-description &quot;ubuntu Base Image-minimal&quot; org.label-schema.docker.cmd &quot;docker run -it ubuntu sh&quot; org.label-schema.vendor &quot;ubuntu&quot; org.label-schema.license &quot;GPLv2&quot; org.label-schema.build-date &quot;20190801&quot;
 ---&gt; Running in 162d2059edb9
 ---&gt; 5525d0accb3e
Removing intermediate container 162d2059edb9
Step 3/4 : ADD ubuntu-base-19.04-base-amd64.tar.gz /
 ---&gt; aa40149e0c02
Step 4/4 : CMD /bin/bash
 ---&gt; Running in aaceddab6dce
 ---&gt; b1ddc781e8b2
Removing intermediate container aaceddab6dce
Successfully built b1ddc781e8b2
Successfully tagged ubuntu19.04base:latest
</code></pre>
<p class="has-line-data" data-line-start="169" data-line-end="170">Run the Image and open the Interactive Terminal</p>
<pre><code class="language-console">$ docker run -it ubuntu19.04base sh 
# cat /etc/os-release
NAME=&quot;Ubuntu&quot;
VERSION=&quot;19.04 (Disco Dingo)&quot;
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME=&quot;Ubuntu 19.04&quot;
VERSION_ID=&quot;19.04&quot;
HOME_URL=&quot;https://www.ubuntu.com/&quot;
SUPPORT_URL=&quot;https://help.ubuntu.com/&quot;
BUG_REPORT_URL=&quot;https://bugs.launchpad.net/ubuntu/&quot;
PRIVACY_POLICY_URL=&quot;https://www.ubuntu.com/legal/terms-and-policies/privacy-policy&quot;
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
# exit
</code></pre>
<p class="has-line-data" data-line-start="189" data-line-end="190">Now that you have a base image installed, you have many choices for what to do next.</p>



				<p>
					Next Reading : <a href="docker-privaterepo.jsp"> Docker Private Repo Setup </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>