<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Docker Private Registry with TLS and Basic AUTH">
<meta name="keywords"content="Docker Private Registry with TLS and Basic AUTH, docker interview questions">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>Docker Private Registry with TLS and Basic AUTH</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/docker-privaterepo.jsp"
  },
  "name" : "Docker Private Registry with TLS and Basic AUTH",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Docker Private Registry with TLS and Basic AUTH",
  "image":"https://8gwifi.org/docs/img/docker.png",
  "datePublished" : "2019-07-29",
  "dateModified": "2019-07-29",
  "articleSection" : "Docker Private Registry with TLS and Basic AUTH",
  "articleBody" : [ "Docker Private Registry with TLS and Basic AUTH","Generate the Certificate", "docker compose file private repo", "Deploying the Private Docker registry with SSL and basic AUTH"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">Docker Private Registry with TLS and Basic AUTH</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Monday July 29th 2019</p>

				<hr>



				<img class="img-fluid rounded" src="img/docker.png"alt="Referefce 8gwifi.org"> 

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>
					<p class="has-line-data" data-line-start="3" data-line-end="4"><strong>Certs Location</strong></p>
<pre><code class="language-console">mkdir -p /opt/certs
cd /opt/certs/
</code></pre>
<p class="has-line-data" data-line-start="10" data-line-end="11"><strong>Generate the Certificate</strong></p>
<p class="has-line-data" data-line-start="12" data-line-end="13">quick self-signed certificate  generate the key/certificate pair, then sign it, all with one openssl line</p>
<pre><code class="html">openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout server.key -out server.crt
</code></pre>
<p class="has-line-data" data-line-start="18" data-line-end="19"><strong>Docker Data Location</strong> : This is where all docker registry Data will be stored</p>
<pre><code class="language-console">mkdir -p /opt/data
</code></pre>
<p class="has-line-data" data-line-start="22" data-line-end="23"><strong>BASIC AUTH Config</strong>: This is where the basic auth realm will be stored</p>
<pre><code class="language-console">mkdir -p /opt/auth
</code></pre>
<p class="has-line-data" data-line-start="26" data-line-end="27"><strong>BASIC AUTH Config File</strong></p>
<pre><code class="language-console">cd /opt
docker run --entrypoint htpasswd   registry:2 -Bbn dockerreg dockerreg &gt; auth/htpasswd
</code></pre>
<p class="has-line-data" data-line-start="34" data-line-end="35"><strong>Deploying the Private Docker registry with SSL and basic AUTH</strong></p>
<p class="has-line-data" data-line-start="36" data-line-end="37">The Registry is deployed as a container  accessible via port 5000. Docker clients will use this domain to access the registry and push/pull images. By specifying a domain, a client can access multiple registries.</p>
<p class="has-line-data" data-line-start="38" data-line-end="39">In this example our Docker registry is located at  DNS  <em>localhost</em></p>
<pre><code class="language-console">docker run -d \
 -p 5000:5000 \
 --restart=always \
 --name registry \
 -v /opt/auth:/auth \
 -e &quot;REGISTRY_AUTH=htpasswd&quot; \
 -e &quot;REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm&quot; \
 -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
 -v /opt/certs:/certs \
 -v /opt/data:/var/lib/registry \
 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt \
 -e REGISTRY_HTTP_TLS_KEY=/certs/server.key \
 registry:2
</code></pre>
<p class="has-line-data" data-line-start="56" data-line-end="57"><strong>Testing the registry Authentication</strong></p>
<pre><code class="html">curl -kiv -H &quot;Authorization: Basic $(echo -n &quot;dockerreg:dockerreg&quot; | base64)&quot; https://localhost:5000/v2/
</code></pre>
<p class="has-line-data" data-line-start="60" data-line-end="61"><strong>Testing the private docker registry</strong></p>
<p class="has-line-data" data-line-start="62" data-line-end="63">First Login to your private repository</p>
<pre><code class="html">docker login localhost:5000
</code></pre>
<p class="has-line-data" data-line-start="66" data-line-end="67">Then</p>
<pre><code class="html">docker pull nginx:latest
docker tag nginx:latest localhost:5000/nginx:latest
docker push localhost:5000/nginx:latest
</code></pre>
<p class="has-line-data" data-line-start="72" data-line-end="73">remove images so they need to be pulled again</p>
<pre><code class="html">docker rmi nginx localhost:5000/nginx
</code></pre>
<p class="has-line-data" data-line-start="76" data-line-end="77">Now pull from the Local repository</p>
<pre><code class="html">docker pull localhost:5000/nginx
</code></pre>
<h2 class="code-line" data-line-start=81 data-line-end=82 ><a id="Setting_up_registry_with_docker_compose_81"></a>Setting up registry with docker compose</h2>
<pre><code class="html">registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
    REGISTRY_HTTP_TLS_KEY: /certs/server.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  volumes:
    - /opt/data:/var/lib/registry
    - /opt/certs:/certs
    - /opt/auth:/auth
</code></pre>
<p class="has-line-data" data-line-start="101" data-line-end="102">Start your registry by issuing the following command in the directory containing the <code>docker-compose.yml</code> file:</p>
<pre><code class="has-line-data" data-line-start="104" data-line-end="106">docker-compose up -d
</code></pre>

				<p>
					Next Reading : <a href="linux-monitor-commands.jsp">How to
						Monitoring All Executed Commands in Linux </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>