<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="How to Install docker on rhel7/ubuntu/centos7/fedora">
<meta name="keywords"content="How to Install docker on rhel7/ubuntu/centos7/fedora, docker interview questions">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>How to Install docker on rhel7/ubuntu/centos7/fedora</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/docker-install.jsp"
  },
  "name" : "How to Install docker on rhel7/ubuntu/centos7/fedora",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "How to Install docker on rhel7/ubuntu/centos7/fedora",
  "image":"https://8gwifi.org/docs/img/docker.png",
  "datePublished" : "2019-08-08",
  "dateModified": "2019-08-08",
  "articleSection" : "Right Way to Install Docker",
  "articleBody" : [ "How to Install Docker on Ubuntu","How to Install Docker on Centos7/RHEL7"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">Right Way to Install Docker on Production Environment</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Tuesday August 08th 2019</p>

				<hr>



				<img class="img-fluid rounded" src="img/docker.png"alt="Referefce 8gwifi.org"> 

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>
					<p class="has-line-data" data-line-start="2" data-line-end="3">In high level to install docker-ce on centos7/rhel7/ubuntu16.04 follow this step</p>
<ul>
<li class="has-line-data" data-line-start="4" data-line-end="5">Setup the Repository</li>
<li class="has-line-data" data-line-start="5" data-line-end="6">Install Packages</li>
<li class="has-line-data" data-line-start="6" data-line-end="7">Add Docker Repo</li>
<li class="has-line-data" data-line-start="7" data-line-end="8">Install Docker know your docker version which you are Installing, this will be usefull when installing docker in multiple nodes, Keep track of the latest verified Docker version</li>
<li class="has-line-data" data-line-start="8" data-line-end="9">Setup daemon: When systemd is chosen as the init system for a Linux distribution, the init process generates and consumes a root control group (<code>cgroup</code>) and acts as a cgroup manager. Systemd has a tight integration with cgroups and will allocate cgroups per process</li>
<li class="has-line-data" data-line-start="9" data-line-end="10">Restart Docker</li>
<li class="has-line-data" data-line-start="10" data-line-end="12">Test It</li>
</ul>
<h2 class="code-line" data-line-start=12 data-line-end=13 ><a id="How_to_Install_Docker_on_Ubuntu_12"></a>How to Install Docker on Ubuntu</h2>


<p><h4>Video Demo </h4> </p>
<iframe width="420" height="315"
src="https://youtube.com/embed/JSUE0iR5hNw">
</iframe>

<p class="has-line-data" data-line-start="16" data-line-end="17">The following installation will set docker version =18.06.2</p>
<pre><code class="has-line-data" data-line-start="19" data-line-end="54" class="language-bash"><span class="hljs-comment"># Install Docker CE</span>
<span class="hljs-comment">## Set up the repository:</span>
<span class="hljs-comment">### Install packages to allow apt to use a repository over HTTPS</span>
apt-get update &amp;&amp; apt-get install apt-transport-https ca-certificates curl software-properties-common

<span class="hljs-comment">### Add Docker’s official GPG key</span>
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

<span class="hljs-comment">### Add Docker apt repository.</span>
add-apt-repository \
  <span class="hljs-string">"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  <span class="hljs-variable">$(lsb_release -cs)</span> \
  stable"</span>

<span class="hljs-comment">## Install Docker CE.</span>
apt-get update &amp;&amp; apt-get install docker-ce=<span class="hljs-number">18.06</span>.<span class="hljs-number">2</span>~ce~<span class="hljs-number">3</span>-<span class="hljs-number">0</span>~ubuntu

<span class="hljs-comment"># Setup daemon.</span>
cat &gt; /etc/docker/daemon.json &lt;&lt;EOF
{
  <span class="hljs-string">"exec-opts"</span>: [<span class="hljs-string">"native.cgroupdriver=systemd"</span>],
  <span class="hljs-string">"log-driver"</span>: <span class="hljs-string">"json-file"</span>,
  <span class="hljs-string">"log-opts"</span>: {
    <span class="hljs-string">"max-size"</span>: <span class="hljs-string">"100m"</span>
  },
  <span class="hljs-string">"storage-driver"</span>: <span class="hljs-string">"overlay2"</span>
}
EOF

mkdir -p /etc/systemd/system/docker.service.d

<span class="hljs-comment"># Restart docker.</span>
systemctl daemon-reload
systemctl restart docker
</code></pre>
<h2 class="code-line" data-line-start=55 data-line-end=56 ><a id="How_to_Install_Docker_on_Centos7RHEL7_55"></a>How to Install Docker on Centos7/RHEL7+</h2>
<p><h4>Video Demo </h4> </p>
<iframe width="420" height="315"
src="https://youtube.com/embed/bO9ZNAoPA6E">
</iframe>

<pre><code class="has-line-data" data-line-start="60" data-line-end="97" class="language-bash"><span class="hljs-comment"># Install Docker CE</span>
<span class="hljs-comment">## Set up the repository</span>
<span class="hljs-comment">### Install required packages.</span>
yum install yum-utils device-mapper-persistent-data lvm2

<span class="hljs-comment">### Add Docker repository.</span>
yum-config-manager \
  --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo

<span class="hljs-comment">## Install Docker CE.</span>
yum update &amp;&amp; yum install docker-ce-<span class="hljs-number">18.06</span>.<span class="hljs-number">2</span>.ce

<span class="hljs-comment">## Create /etc/docker directory.</span>
mkdir /etc/docker

<span class="hljs-comment"># Setup daemon.</span>
cat &gt; /etc/docker/daemon.json &lt;&lt;EOF
{
  <span class="hljs-string">"exec-opts"</span>: [<span class="hljs-string">"native.cgroupdriver=systemd"</span>],
  <span class="hljs-string">"log-driver"</span>: <span class="hljs-string">"json-file"</span>,
  <span class="hljs-string">"log-opts"</span>: {
    <span class="hljs-string">"max-size"</span>: <span class="hljs-string">"100m"</span>
  },
  <span class="hljs-string">"storage-driver"</span>: <span class="hljs-string">"overlay2"</span>,
  <span class="hljs-string">"storage-opts"</span>: [
    <span class="hljs-string">"overlay2.override_kernel_check=true"</span>
  ]
}
EOF

mkdir -p /etc/systemd/system/docker.service.d

<span class="hljs-comment"># Restart Docker</span>
systemctl daemon-reload
systemctl restart docker
</code></pre>



				<p>
					Next Reading : <a href="docker-privaterepo.jsp">How to Setup Docker Private Repository </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>