<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="onlinie learning Pre-Primary Teacher">
<meta name="keywords"content="online learning, effective way to teach online">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>5 Reasons why Online learning is New Danger to Pre-Primary Teacher</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/gen-learning.jsp"
  },
  "name" : "5 Reasons why Online learning is New Danger to Pre-Primary Teacher",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "5 Reasons why Online learning is New Danger to Pre-Primary Teacher",
  "image":"https://8gwifi.org/docs/img/gen-l1.jpg",
  "datePublished" : "2020-05-17",
  "dateModified": "2020-05-17",
  "articleSection" : "5 Reasons why Online learning is New Danger to Pre-Primary Teacher",
  "articleBody" : [ "online teaching" , "online teaching with kids"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">5 Reasons why Online learning is New Danger to Pre-Primary Teacher  ??</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Teacher</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Sunday May 16th 2020</p>

				<hr>



				<img class="img-fluid rounded" src="img/gen-l1.jpg"alt="Referefce 8gwifi.org"> 

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>
<p class="has-line-data" data-line-start="2" data-line-end="3">Amid the crisis of coronavirus social distancing is the new norm, schools are finding a new method to deliver the content and finding a new way to adopt effective teaching. Various Model is getting trying, some of the school is delivering the recorded Video and asking the student to complete the assignment, on the contrary, some of the school is trying to have Interactive session with the class students.</p>
<p class="has-line-data" data-line-start="4" data-line-end="5">My wife, she is a school teacher for class 1-4 has now adopted the technology to move forward. She is putting all the effort and engaging with other teachers in a methodological way, she needs to be ready before the school resume. Within this new normal she has learned various new platforms like how to do meeting effectively, mocking class sessions, raising questions, and try creating the exact replica of the school class environment in a virtual environment.</p>
<p class="has-line-data" data-line-start="6" data-line-end="7">Despite all the methods they are adopting new Danger to themself here and how</p>
<ol>
<li class="has-line-data" data-line-start="8" data-line-end="10"><mark>Online Teaching Vs Teaching method</mark></li>
</ol>
<p class="has-line-data" data-line-start="10" data-line-end="11">Many students who are joining the online classes, know their teacher up-front and same goes to the teacher, but what about the parents ??, they are new hidden entry to the classroom, they are silently observing the teacher who is trying to deliver the content, their attention is nowhere in there Kids, instead, they are trying to find how can these teachers be booked, We understand Many parents will not do so, but in this practical world Majority of the conscious parent will do this behavior un-causally.</p>
<p class="has-line-data" data-line-start="12" data-line-end="13">In a class of 30 students as average, the teacher is trying to deliver the content, the teacher depends on the Technology (the new Factor ) to deliver the right content to there student as per approved syllabus by there governing body.</p>
<p class="has-line-data" data-line-start="14" data-line-end="15">With all this 30 student, let say on average 20 students will have a parent at there home, which makes the class of 50 People, Now the teacher has not trained to tackle this kind of Mix environment to deal with, even these classes are recorded for the training purpose, imagine a parent conversion is recorded which will trigger un-necessary conflict to another parent why he asking the question and the entire classroom will get compromised</p>
<img class="img-fluid rounded" src="img/gen-l2.jpg"alt="Referefce 8gwifi.org"> 
<ol start="2">
<li class="has-line-data" data-line-start="16" data-line-end="18"><mark>Online Teaching vs Technology</mark></li>
</ol>
<p class="has-line-data" data-line-start="18" data-line-end="19">Kids are smarter these days, they know the system better than there parents and their teacher, it gives them complete freedom on how to abuse them, the teacher doesn’t have any control to say anything to KIds, as in background their parent will be listening to the conversation. This biassed relation-ship between Teacher-Technology-Kids-Parent will never establish a formal conversation to carried upon.</p>
<ol start="3">
<li class="has-line-data" data-line-start="21" data-line-end="23"><mark>Online Teaching vs Mental Health</mark></li>
</ol>
<p class="has-line-data" data-line-start="23" data-line-end="24">Most of the teacher who is in this profession, see this as an opportunity to explore themself, they just need to get out from there house and perform in there work field, Yes I say they need to go out from the house, now with this crisis, this opportunity is lost and their Motivation factor also, they need to take of day-2-day issues and at the same time in the same environment, they need to work which can affect their Mental health. Mental health is not a headache, it’s a process which positively keeps our thinking.</p>
<ol start="4">
<li class="has-line-data" data-line-start="25" data-line-end="27"><mark>Online Teaching Vs Behaviour</mark></li>
</ol>
<p class="has-line-data" data-line-start="27" data-line-end="28">Well the behavior aspect of Teacher represents the teacher personality, it attaches to the kid in must faster away, now the teacher expressions will be restricted to one small screen where the student is listening and there will not be any emotional connect, and where is no emotional connect there is no Interest to evolve and communication will be always one-way, Teacher will also have difficulty to learn the student behavior as there student will static most of the time, at least in school they will talk to someone when Teachers away do some chit-chatting which creates Interest in coming to school. The school is not about the study always, it’s a behavior practice which makes social to each Other and with the absence of this social practice will result in greater Isolation for both the Teacher and Kids</p>
<ol start="5">
<li class="has-line-data" data-line-start="29" data-line-end="31"><mark>Online Teaching Vs Feel</mark></li>
</ol>
<p class="has-line-data" data-line-start="31" data-line-end="32">Is Online assignment is really bad ?? no matter how good they are designed, take a step back, the online assignment just takes out the smell and feel of physical objects like (Pens, Paper, books, etc) which are used in a daily school activity. The teachers are started making good PPT and trying to explain things, That’s good in that process to cope up with the new requirement on the other side they have to abolish the good technique of feeling of these Objects. There is no deniable good PPT that can explain things in a much better way, but that depends on the quality of the production of those PPT, there is a third party that can do this stuff, but the schools are not ready to deliver those high-quality content for the Student. The feel is important for everyone as it touches the senses and your body sees some changes good or bad it’s up to</p>
				<hr>
				
				<hr>

<%@ include file="footer_adsense.jsp"%> 
<p><strong> Thanku for reading !!! Give a Share for Support</strong></p>
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a04129f05073300123e3782&product=inline-share-buttons"></script>   
<div class="sharethis-inline-share-buttons"></div>

<hr>
				
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				



				<!-- Topic Widget -->
				<%-- <%@ include file="side.jsp"%> --%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>