<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="add ipv6 support to your clous provider aws,ec2,alicloud,linode,digital ocean">
    <meta name="keywords" content="add ipv6 support to your cloud provider aws,ec2,alicloud,linode,digital ocean,azure, tunnel broker, hurricane electric, ipv6 network interfaces configuration">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>Add ipv6 support to your clous provider aws,ec2,alicloud,linode,digital ocean </title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/he-ipv6.jsp"
  },
  "name" : "Add IPv6 support to your ECS Instances",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "add ipv6 support to your clous provider aws,ec2,alicloud,linode,digital ocean",
  "image":"Create_New_Tunnel2.png",
  "datePublished" : "2018-07-30",
  "dateModified": "2018-07-30",
  "articleSection" : "Adding Native IPv6 Support to ECS Instance",
  "articleBody" : [ "Tunnel broker", "Hurricane Electric Tunnel broker","Format of assigned IPv6 addresses","Creating HE Tunnel","Configure ECS Interface","el6 configuration","Debian Ubuntu","Windows 10 hurricane electric","Verify the tunnel is working"]
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4" id="addingnativeipv6supporttoecsinstance">Adding Native IPv6 Support to ECS Instance</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Monday July 30, 2018</p>
          </p>
          
          <img class="img-fluid rounded" src="img/Create_New_Tunnel2.png" height="400" width="400" alt="Referefce ">
          
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>



<p>This document provides an overview of various ways to tunnel IPv6  packets over IPv4 networks in ECS Instances<blockquote>You can Add an routable IPv6 address in Cloud provider like  Alicloud,Linonde,DigitalOcean</blockquote></p>


<h1 class="mt-4" id="beforeyoubegin">Before you Begin</h1>

<p>Make Sure you have following prerequisites met on the <strong>ECS Side</strong>  running on any cloud Provider</p>

<table class="table table-striped">
<tr>
<th>Precondition</th>
<th>Check</th>
</tr>
<tr>
<td>
ECS Instance is <strong>up and Running</strong> 
</td>
<td>
Pass
</td>
</tr>

<tr>
<td>
Having <strong>sudo</strong> privilege account or <strong>root</strong> account
</td>
<td>
Pass
</td>
</tr>

<tr>
<td>
ECS Instance is assigned <strong>with public IP</strong>
</td>
<td>
Pass
</td>
</tr>

<tr>
<td>
ECS Instance Security Group <strong>Allowing ICMP</strong>
</td>
<td>
Pass
</td>
</tr>
</table>



<h1 class="mt-4" id="tunnelbroker">Tunnel broker:</h1>

<p>A service that provides tunneled connectivity to the  IPv6 Internet. Using Tunnel Broker an IPv6 access service  can enable ECS Instances to access over IPv6 .</p>

<p>Few example of Tunnel brokers Providers </p>

<ul>
<li><a href="https://www.sixxs.net/main/">SixXS</a> - IPv6 Deployment &amp; Tunnel Broker</li>

<li><a href="https://www.tunnelbroker.net/">tunnelbroker.net</a> - Hurricane Electric Free IPv6 Tunnel Broker</li>

<li><a href="https://www.freenet6.net/">gogo6</a> Freenet6: Free and Easy IPv6 Connectivity</li>
</ul>

<h2 class="mt-4" id="hurricaneelectrictunnelbroker">Hurricane Electric Tunnel broker</h2>

<p>In this example we are using HE, tunnel provider </p>

<h3 id="formatofassignedipv6addresses">Format of assigned IPv6 addresses</h3>

<p>The prefix length assigned to configured tunnels is <strong>128 bits (/128).</strong> Tunnels are assigned from prefix <strong>2001:470::/32</strong> </p>

<h2 class="mt-4" id="creatinghetunnel">Creating HE Tunnel</h2>

<p>Before creating a Tunnel make sure your <strong>ECS instance is up and running</strong>  and having a routable IPv4 (Ex: 34.218.239.239) assigned </p>

<ol>
<li>Create an Account in <a href="https://www.tunnelbroker.net/">HE</a> </li>

<li>Create Regular Tunnel </li>

<li>When creating new tunnel provide the ECS IP address as show in the diagram</li>

<li>Select the <strong>Location which is very close to Alicloud Region</strong> to avoid any Latency Issues </li>
</ol>

<p><img class="img-fluid rounded"  src="img/Create_New_Tunnel.png" alt="enter image description here" /></p>

<ol>
<li>Once the IPv6 tunnel is created in the HE, you will be displayed with Summary page <strong>with tunnel Endpoints</strong> note down to the new endpoint configuration</li>
</ol>

<p><img class="img-fluid rounded"  src="img/Create_New_Tunnel2.png" alt="" /></p>

<h2 class="mt-4" id="configureecsinterface">Configure ECS Interface</h2>

<h2 class="mt-4" id="forel6">For EL6</h2>

<p>if the ECS instances running on <strong>General linux configure <em>*  two new interfaces *</em>sit0</strong> for <strong>tunnel <em>*  and *</em>sit1</strong> for <strong>ipv6 address</strong> </p>

<p>|tunnel| ipv6 |
|--|--|
| sit0 |  sit1|
| ::216.66.22.2 |  2001:470:7:20a::2/64|</p>

<p>Copy and paste the following commands into a command window:</p>

<pre><code class="html">ifconfig sit0 up
ifconfig sit0 inet6 tunnel ::216.66.22.2
ifconfig sit1 up
ifconfig sit1 inet6 add 2001:470:7:20a::2/64
route -A inet6 add ::/0 dev sit1
</code></pre>

<p>Check the new interfaces is added <strong>sit1</strong> is your IPv6 address which is added to the ECS Instance</p>

<pre><code class="html">[root@ip-172-31-20-124 ~]# ifconfig 
        eth0: flags=4163&lt;UP,BROADCAST,RUNNING,MULTICAST&gt;  mtu 1500
                inet 172.31.20.124  netmask 255.255.240.0  broadcast 172.31.31.255
                inet6 fe80::8e:5fff:fe78:dc2c  prefixlen 64  scopeid 0x20&lt;link&gt;
                ether 02:8e:5f:78:dc:2c  txqueuelen 1000  (Ethernet)
                RX packets 11345  bytes 15649422 (14.9 MiB)
                RX errors 0  dropped 0  overruns 0  frame 0
                TX packets 1097  bytes 99162 (96.8 KiB)
                TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    lo: flags=73&lt;UP,LOOPBACK,RUNNING&gt;  mtu 65536
            inet 127.0.0.1  netmask 255.0.0.0
            inet6 ::1  prefixlen 128  scopeid 0x10&lt;host&gt;
            loop  txqueuelen 1000  (Local Loopback)
            RX packets 8  bytes 648 (648.0 B)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 8  bytes 648 (648.0 B)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    sit0: flags=193&lt;UP,RUNNING,NOARP&gt;  mtu 1480
            inet6 ::127.0.0.1  prefixlen 96  scopeid 0x90&lt;compat,host&gt;
            inet6 ::172.31.20.124  prefixlen 96  scopeid 0x80&lt;compat,global&gt;
            sit  txqueuelen 1000  (IPv6-in-IPv4)
            RX packets 0  bytes 0 (0.0 B)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 0  bytes 0 (0.0 B)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    sit1: flags=209&lt;UP,POINTOPOINT,RUNNING,NOARP&gt;  mtu 1480
            inet6 2001:470:7:20a::2  prefixlen 64  scopeid 0x0&lt;global&gt;
            inet6 fe80::ac1f:147c  prefixlen 64  scopeid 0x20&lt;link&gt;
            sit  txqueuelen 1000  (IPv6-in-IPv4)
            RX packets 0  bytes 0 (0.0 B)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 0  bytes 0 (0.0 B)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
</code></pre>

<h2 class="mt-4" id="forel7">For EL7</h2>

<p>Copy and paste the following commands into a command window by adjusting with your tunnel configuration </p>

<pre><code class="html">modprobe ipv6
ip tunnel add he-ipv6 mode sit remote 216.66.22.2 local 34.218.239.239 ttl 255
ip link set he-ipv6 up
ip addr add 2001:470:7:20a::2/64 dev he-ipv6
ip route add ::/0 dev he-ipv6
ip -f inet6 addr
</code></pre>

<h2 class="mt-4" id="fordebianubuntu">For Debian Ubuntu</h2>

<p>Paste the following into <strong>/etc/network/interfaces:</strong> and adjust </p>

<pre><code class="html">auto he-ipv6
iface he-ipv6 inet6 v4tunnel
        address 2001:470:7:20a::2
        netmask 64
        endpoint 216.66.22.2
        local 34.218.239.239
        ttl 255
        gateway 2001:470:7:20a::1
</code></pre>

<h2 class="mt-4" id="windows10">Windows 10</h2>

<p>Copy and paste the following commands into a command window:</p>

<pre><code class="html">netsh interface teredo set state disabled
netsh interface ipv6 add v6v4tunnel interface=IP6Tunnel localaddress=34.218.239.239 remoteaddress=216.66.22.2
netsh interface ipv6 add address interface=IP6Tunnel address=2001:470:7:20a::2
netsh interface ipv6 add route prefix=::/0 interface=IP6Tunnel nexthop=2001:470:7:20a::1
</code></pre>

<h2 class="mt-4" id="verifythetunnelisworking">Verify the tunnel is working</h2>

<p>To verify you need to perform  <strong>ping6</strong></p>

<pre><code class="html">$ ping6 -c4 2001:470:7:20a::1 
PING 2001:470:7:20a::1(2001:470:7:20a::1) 56 data bytes
64 bytes from 2001:470:7:20a::1: icmp_seq=1 ttl=44 time=76.5 ms
64 bytes from 2001:470:7:20a::1: icmp_seq=2 ttl=44 time=76.5 ms
64 bytes from 2001:470:7:20a::1: icmp_seq=3 ttl=44 time=76.5 ms
64 bytes from 2001:470:7:20a::1: icmp_seq=4 ttl=44 time=76.6 ms

--- 2001:470:7:20a::1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 76.515/76.563/76.653/0.343 ms
</code></pre>

<p>Alternatively you can use any <a href="https://8gwifi.org/pingfunctions.jsp">Online Ipv6 ping</a> the check Ipv6 address </p>

<p><img class="img-fluid rounded"  src="img/Create_New_Tunnel3.png" alt="" /></p>
<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 
         
         <%@ include file="related-cryptography.jsp"%>
         <%@ include file="related-window-crypto.jsp"%>
         
         <%@ include file="related-linux.jsp"%>

          <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         <%@ include file="related-openstack.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>