<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="what is kubernetes namespace, kubernetes create namespace, kubernetes delete namespace, launch pod in a given namespace">
    <meta name="keywords" content="namespaces in kubernetes, kubernetes tutorial, kubernetes by examples, kubernetes interview questions ">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>Kubernetes Namespace</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/kube-namespaces.jsp"
  },
  "name" : "Kubernetes Namespace",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Kubernetes Namespace",
  "image":"https://8gwifi.org/docs/img/kube-namespaces.png",
  "datePublished" : "2019-02-06",
  "dateModified": "2019-02-06",
  "articleSection" : "Kubernetes namespaces",
  "articleBody" : [ "Introduction" ,"Kubernetes namespaces" , "creating namespace" , "Viewing namespace" , "View the pods running on kube-system namespace" , "Deleting the Namespace" ],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Kubernetes Namespace</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Wednesday February 6, 2019</p>
          </p>
          
          <img class="img-fluid rounded" src="img/kube-namespaces.png" height="400" width="500" alt="Referefce ">
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>

<h3 class="mt-4">Introduction </h3>

<p>A Kubernetes namespace provides a mechanism to scope resources in a cluster.</p>
<p>Namespaces provide a unique scope for:</p>
<ul>
<li>
<p>Named resources to avoid basic naming collisions.</p>
</li>
<li>
<p>Delegated management authority to trusted users.</p>
</li>
<li>
<p>The ability to limit community resource consumption.</p>
</li>
</ul>
<p>Most objects in the system are scoped by namespace, but some are excepted and have no namespace, including nodes and users.</p>
<p><strong>Viewing namespace</strong></p>
<p>The following command can be used to get a list of all namespaces:</p>
<pre><code class="language-console">root@kube-master:# kubectl get namespaces
NAME  STATUS  AGE
default Active  13d
kube-public Active  13d
kube-system Active  13d
</code></pre>
<p>Kubernetes starts with three initial namespaces:</p>
<ul>
<li><code>default</code>  The default namespace for objects with no other namespace</li>
<li><code>kube-system</code>  The namespace for objects created by the Kubernetes system</li>
<li><code>kube-public</code>  This namespace is created automatically and is readable by all users (including those not authenticated).</li>
</ul>
<p><strong>View the pods running on kube-system namespace</strong></p>
<pre><code class="language-console">root@kube-master:# kubectl get pods -n kube-system
NAME                                  READY     STATUS    RESTARTS   AGE
coredns-78fcdf6894-rbfq8              1/1       Running   0          13d
coredns-78fcdf6894-ttbqz              1/1       Running   0          13d
etcd-kube-master                      1/1       Running   0          13d
kube-apiserver-kube-master            1/1       Running   0          13d
kube-controller-manager-kube-master   1/1       Running   0          13d
kube-flannel-ds-hzz8t                 1/1       Running   0          13d
kube-flannel-ds-vsr2h                 1/1       Running   0          13d
kube-proxy-5vmws                      1/1       Running   0          13d
kube-proxy-7zm5v                      1/1       Running   0          13d
kube-scheduler-kube-master            1/1       Running   0          13d
tiller-deploy-85744d9bfb-qj9p4        1/1       Running   0          13d
</code></pre>
<p><strong>Creating Namespace</strong></p>
<p>A <strong>namespace</strong> allows a community of users to organize and manage their content in isolation from other communities. Users must be given access to projects by administrators, or if allowed to create projects, automatically have access to their own projects.</p>
<p>The YAML definition of creating the namespace with</p>
<blockquote>
<p>kind:Namespace</p>
</blockquote>
<pre><code class="language-console">{
    &quot;kind&quot;: &quot;Namespace&quot;,
    &quot;apiVersion&quot;: &quot;v1&quot;,
    &quot;metadata&quot;: {
        &quot;name&quot;: &quot;prod&quot;,
        &quot;labels&quot;: {
            &quot;name&quot;: &quot;prod&quot;
        }
    }
}
</code></pre>
<p>The following command will create for namespace which will be used for devops purpose namely <strong>DEV,PROD,QA,STAG</strong> under which the resources would be managed accordingly.</p>
<pre><code class="language-console">root@kube-master:# kubectl create -f https://raw.githubusercontent.com/anishnath/kubernetes/master/devops-namespace.yaml
namespace/dev created
namespace/prod created
namespace/qa created
namespace/stag created
</code></pre>
<p><strong>Viewing namespace with labels</strong></p>
<pre><code class="language-console">root@kube-master:# kubectl get namespaces --show-labels
NAME          STATUS    AGE       LABELS
default       Active    13d       &lt;none&gt;
dev           Active    58s       name=dev
kube-public   Active    13d       &lt;none&gt;
kube-system   Active    13d       &lt;none&gt;
prod          Active    58s       name=prod
qa            Active    58s       name=qa
stag          Active    58s       name=stag
</code></pre>
<ul>
<li>A Kubernetes namespace provides the scope for Pods, Services, and Deployments in the cluster.</li>
<li>Users interacting with one namespace do not see the content in another namespace.</li>
</ul>
<p><strong>Launch a busy box pods in qa namespace</strong></p>
<pre><code class="language-console">root@kube-master:# kubectl create -f https://raw.githubusercontent.com/anishnath/kubernetes/master/busybox.yaml -n qa
pod/busybox created
root@kube-master:# kubectl get pods -n qa 
NAME      READY     STATUS    RESTARTS   AGE
busybox   1/1       Running   0          12s
</code></pre>
<p><strong>Launch a busy box pods in dev namespace</strong></p>
<pre><code class="language-console">root@kube-master:# kubectl create -f https://raw.githubusercontent.com/anishnath/kubernetes/master/busybox.yaml -n dev
pod/busybox created
root@kube-master:# kubectl get pods -n dev
NAME      READY     STATUS    RESTARTS   AGE
busybox   1/1       Running   0          8s
</code></pre>
<p><strong>Deleting the Namespace</strong></p>
<pre><code class="language-console">root@kube-master:# kubectl delete namespace dev
namespace &quot;dev&quot; deleted
</code></pre>
<p><strong>Warning:</strong> When a namespace is deleted, it will delete all the associated k8 resource along with.</p>
          



<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
          <%@ include file="related-kube.jsp"%>
          
          <!-- Article Widget -->
         <%@ include file="related-linux.jsp"%>
         
           <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         <%@ include file="related-window-crypto.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>