<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="kubernetes service external ip pending">
    <meta name="keywords" content="kubernetes service external ip pending  kubernetes tutorial, kubernetes by examples">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>kubernetes service external ip pending</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/kube-debug.jsp"
  },
  "name" : "kubernetes service external ip pending",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "kubernetes service external ip pending",
  "image":"https://8gwifi.org/docs/img/kube-install.png",
  "datePublished" : "2019-01-18",
  "dateModified": "2019-01-18",
  "articleSection" : "kubernetes service external ip pending",
  "articleBody" : [ "kubernetes service external ip pending" ],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">kubernetes service external ip pending</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Friday January 18, 2019</p>
          </p>
          
          <img class="img-fluid rounded" src="img/kube-install.png" height="400" width="500" alt="Referefce ">
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>

<p>This sample chapter extracted from the book,<mark> <a href="https://leanpub.com/crypto">Kubernetes for DevOps </a>. </mark> </p>
<p><mark>Get this book on Just  <a href="https://leanpub.com/kube/" target="_blank" rel="noopener">  $9 </a> or Ask Author for Discount </mark>   </p>
<p><iframe class="embed-responsive-item" width='160' height='400' src='https://leanpub.com/kube/embed' frameborder='0' allowtransparency='true'></iframe></p>

<hr>

<p>Well if you stuck in solving the problem of &quot;<strong>kubernetes service external ip pending</strong>&quot;, let's visit the k8 concept once more time.</p>
<ul>
<li>Run a Hello World application in your cluster:</li>
</ul>
<pre><code class="language-console"># kubectl run hello-world --replicas=2 --labels=&quot;run=LoadBalancer&quot; --image=gcr.io/google-samples/node-hello:1.0  --port=8080
<mark>deployment.apps/hello-world created</mark>
</code></pre>
<ul>
<li>Create a Service object that exposes the deployment:</li>
</ul>
<pre><code class="language-console"># kubectl expose deployment hello-world --type=LoadBalancer --name=lb-service
<mark>service/lb-service exposed</mark>
</code></pre>
<ul>
<li>Display information about the Service:</li>
</ul>
<pre><code class="language-console"># kubectl get services lb-service
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
lb-service   <mark>LoadBalancer</mark>   10.102.78.66   <mark>&lt;pending&gt;</mark>     8080:31031/TCP   1m
</code></pre>
<p>After you create the service, it takes time for the cloud infrastructure to create the load balancer and write its IP address into the Service object</p>
<p>Well All the time passes still <strong>kubernetes service external ip pending</strong> ?</p>
<p>If Kubernetes is running in an environment that <strong>doesn't support LoadBalancer services,</strong> the load balancer <strong>will not be provisioned</strong>, but the service will still behave like a <strong>NodePort service</strong>, your <strong>cloud/K8</strong> engine should support LoadBalancer Service</p>
<p>In that case if you manage to add or EIP or VIP to your node then you can attach to the EXTERNAL-IP of your TYPE=LoadBalancer in k8 cluster, for example attaching the EIP/VIP address to the node <code>172.16.2.13</code></p>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl patch svc lb-service  -p '{&quot;spec&quot;: {&quot;type&quot;: &quot;LoadBalancer&quot;, &quot;externalIPs&quot;:[&quot;172.16.2.13&quot;]}}'
service/lb-service patched
</code></pre>
<ul>
<li>Display information about the Service:</li>
</ul>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl get services lb-service
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S)  AGE
lb-service LoadBalancer 10.102.78.66 <mark>172.16.2.13</mark> 8080:31031/TCP 10m
</code></pre>
<ul>
<li>so you can now access the service at that IP address</li>
</ul>
<pre><code class="language-console">root@kube-master:/home/ansible# curl 172.16.2.13:8080
<mark>Hello Kubernetes!</mark>
</code></pre>

<p>since it's kubernetes you may encounter some issues, feel free to poke me</p>


<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
          <%@ include file="related-kube.jsp"%>
          
          <!-- Article Widget -->
         <%@ include file="related-linux.jsp"%>
         
           <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         <%@ include file="related-window-crypto.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>