<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="How to install traefik in kubernetes helm,traefik basic auth, traefik ui 404, traefik ssl configuration, kubernetes tutorial">
    <meta name="keywords" content="traefik in kubernetes helm, traefik kubernetes installaion, helm traefik install, traefik PersistentVolume, PersistentVolumeClaim, externel ip pending kubernetes, kubernetes tutorial, kubernetes by examples">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>How to install and configure traefik in kubernetes helm</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/kube-traefik.jsp"
  },
  "name" : "How to install traefik in kubernetes helm",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Kubernetes traefik Installation (helm)",
  "image":"https://8gwifi.org/docs/img/kube-traefik.png",
  "datePublished" : "2019-01-18",
  "dateModified": "2019-01-18",
  "articleSection" : "Kubernetes traefik Installation (helm)",
  "articleBody" : [ "Introduction" ,"kubernetes Installation starts here", "About traefik" , "helm init" , "View the traefik cluster role" ,  "traefik dashbaord access" , "traefik basic auth" , "traefik ssl configuration" ],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Kubernetes Traefik Installation (helm)</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Friday January 18, 2019</p>
          </p>
          
          <img class="img-fluid rounded" src="img/traefik.png" height="400" width="500" alt="Referefce ">
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>

<h3 class="mt-4">Introduction </h3>
<p>In this article we will learn how to to setup <strong>traefik</strong> in kubernetes cluster using helm</p>
<p><a href="helm.sh">Helm</a>: Helm is a tool for managing Kubernetes charts. Charts are packages of pre-configured Kubernetes resources.</p>
<ul>
<li>Let's Begin deploying <strong>traefik</strong> using helm in <strong>traefik</strong> , if you are new to helm then download and initialize helm as follows</li>
</ul>
<pre><code class="language-console">root@kube-master:#  helm init
root@kube-master:# kubectl create serviceaccount --namespace kube-system tiller
root@kube-master:# kubectl create clusterrolebinding tiller-cluster-rule \
   --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
root@kube-master:#  kubectl patch deploy --namespace kube-system tiller-deploy \
   -p '{&quot;spec&quot;:{&quot;template&quot;:{&quot;spec&quot;:{&quot;serviceAccount&quot;:&quot;tiller&quot;}}}}'
</code></pre>
<ul>
<li>Make sure the title-deploy pod is up and running</li>
</ul>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl get pods -n kube-system 
NAME                                  READY     STATUS    RESTARTS   AGE
coredns-78fcdf6894-jvmlb              1/1       Running   0          1h
coredns-78fcdf6894-xstbn              1/1       Running   0          1h
etcd-kube-master                      1/1       Running   0          1h
kube-apiserver-kube-master            1/1       Running   0          1h
kube-controller-manager-kube-master   1/1       Running   0          1h
kube-flannel-ds-5gzn9                 1/1       Running   0          1h
kube-flannel-ds-tlc8j                 1/1       Running   0          1h
kube-proxy-kl4fg                      1/1       Running   0          1h
kube-proxy-krt6n                      1/1       Running   0          1h
kube-scheduler-kube-master            1/1       Running   0          1h
tiller-deploy-85744d9bfb-wh98g        1/1       Running   0          1h
</code></pre>
<ul>
<li>Once titler pod is up and running, <strong>traefik</strong> Installation starts here, this is done through helm the kubernetes package manager,</li>
</ul>
<h2><a id="About_traefik_37"></a>About traefik</h2>
<p><a href="https://traefik.io/"> Traefik</a> is a modern HTTP reverse proxy and load balancer made to deploy microservices with ease.</p>
<ul>
<li>In the below command line, we enabled the dashboard (<code>dashboard.enabled=true</code>) and made it available on <a href="http://dashboard.traefik">http://dashboard.traefik</a> (<code>dashboard.domain=dashboard.traefik</code>). Since the installation is performed in barematel  set the <code>serviceType=NodePort</code>, you ignore this field if you have load-balancer enabled, we tell the helm to setup the cluster role binding by setting  <code>rbac.enabled=true</code></li>
<li>The traefik ingress is installed in the <strong>kube-system</strong> namespace</li>
</ul>
<pre><code class="language-console">helm install stable/traefik --name traefik --set dashboard.enabled=true,serviceType=NodePort,dashboard.domain=dashboard.traefik,rbac.enabled=true  --namespace kube-system

NAME:   traefik
LAST DEPLOYED: Fri Jan 18 10:20:11 2019
NAMESPACE: kube-system
STATUS: DEPLOYED

RESOURCES:
==&gt; v1/ServiceAccount
NAME     SECRETS  AGE
traefik  1        3s

==&gt; v1/ClusterRole
NAME     AGE
traefik  3s

==&gt; v1/ClusterRoleBinding
NAME     AGE
traefik  3s

==&gt; v1/Service
NAME               TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)                     AGE
traefik-dashboard  ClusterIP  10.111.208.113  &lt;none&gt;       80/TCP                      3s
traefik            NodePort   10.106.144.153  &lt;none&gt;       80:31622/TCP,443:31703/TCP  2s

==&gt; v1/Deployment
NAME     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
traefik  1        1        1           0          2s

==&gt; v1beta1/Ingress
NAME               HOSTS              ADDRESS  PORTS  AGE
traefik-dashboard  dashboard.traefik  80       2s

==&gt; v1/Pod(related)
NAME                     READY  STATUS             RESTARTS  AGE
traefik-8dc967bf9-89cb2  0/1    ContainerCreating  0         2s

==&gt; v1/ConfigMap
NAME     DATA  AGE
traefik  1     3s

NOTES:

1. Traefik has been started. You can find out the port numbers being used by traefik by running:

          $ kubectl describe svc traefik --namespace kube-system

2. Configure DNS records corresponding to Kubernetes ingress resources to point to the NODE_IP/NODE_HOST
</code></pre>
<ul>
<li>View the cluster role</li>
</ul>
<pre><code class="language-console">root@kube-master:# kubectl describe clusterrole traefik
Name:         traefik
Labels:       &lt;none&gt;
Annotations:  &lt;none&gt;
PolicyRule:
  Resources                    Non-Resource URLs  Resource Names  Verbs
  ---------                    -----------------  --------------  -----
  endpoints                    []                 []              [get list watch]
  pods                         []                 []              [get list watch]
  secrets                      []                 []              [get list watch]
  services                     []                 []              [get list watch]
  ingresses.extensions         []                 []              [get list watch]
  ingresses.extensions/status  []                 []              [update]
</code></pre>
<ul>
<li>Check the <strong>traefik</strong> pods are running in the kube-system namespace</li>
</ul>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl get pods  -n kube-system | grep traefik
traefik-8dc967bf9-89cb2               1/1       Running   0          17m
</code></pre>
<ul>
<li>Traefik has been started. You can find out the port numbers being used by traefik by running:</li>
</ul>
<pre><code class="language-console">root@kube-master:# kubectl describe svc traefik --namespace kube-system
Name:                     traefik
Namespace:                kube-system
Labels:                   app=traefik
                          chart=traefik-1.58.0
                          heritage=Tiller
                          release=traefik
Annotations:              &lt;none&gt;
Selector:                 app=traefik,release=traefik
Type:                     NodePort
IP:                       10.106.144.153
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  31622/TCP
Endpoints:                10.244.1.81:80
Port:                     https  443/TCP
TargetPort:               httpn/TCP
NodePort:                 https  31703/TCP
Endpoints:                10.244.1.81:8880
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   &lt;none&gt;
</code></pre>
<ul>
<li>View the helm chart deployment</li>
</ul>
<pre><code class="language-console">root@kube-master:# helm ls 
NAME    REVISION  UPDATED                   STATUS    CHART           APP VERSION NAMESPACE  
traefik 1         Fri Jan 18 10:20:11 2019  DEPLOYED  traefik-1.58.0  1.7.6       kube-system
</code></pre>
<ul>
<li>Open the web browser and browse Node port <a href="http://dashboard.traefik:31622/">http://dashboard.traefik:31622/</a> to access Traefik page</li>
</ul>
<p><img class="img-fluid rounded" src="img/traefik.png" alt=""></p>
<ul>
<li>Note: The installed <strong>traefik</strong> is over http and there is no form of Authentication, in order to provide the basic authentication</li>
<li>To configure BASIC AUTH Use <code>htpasswd</code> to create a file containing the username and the MD5-encoded password:</li>
</ul>
<pre><code class="language-console">root@kube-master:# htpasswd -c traefik traefik
New password: &lt;&lt;traefik&gt;&gt;
Re-type new password:&lt;&lt;traefik&gt;&gt;
</code></pre>
<ul>
<li>Deploy <strong>traefik</strong> with <code>dashboard.auth.basic</code> Enabled</li>
</ul>
<pre><code class="language-console">root@kube-master:# helm install stable/traefik --name traefik --set dashboard.enabled=true,serviceType=NodePort,dashboard.domain=dashboard.traefik,rbac.enabled=true,dashboard.auth.basic.traefik='$apr1$vUmd7ddA$CoklUZpHBbRzvnZUz6eFY.' --namespace kube-system
</code></pre>
<ul>
<li>Open the web browser and browse Node port <a href="http://dashboard.traefik">http://dashboard.traefik</a>:&lt;NODE_PORT&gt;/ to access Traefik page</li>
<li>Give username and password as <strong>traefik:traefik</strong><br>
<img class="img-fluid rounded" src="img/traefik1.png" alt=""></li>
<li>Enable SSL, this can be done through by setting the <code>ssl.enabled=true</code></li>
<li>Deploy <strong>traefik</strong> with BASIC AUTH and SSL Enabled</li>
</ul>
<pre><code class="language-console">root@kube-master:# helm install stable/traefik --name traefik --set dashboard.enabled=true,serviceType=NodePort,dashboard.domain=dashboard.traefik,rbac.enabled=true,dashboard.auth.basic.traefik='$apr1$vUmd7ddA$CoklUZpHBbRzvnZUz6eFY.',ssl.enabled=true,ssl.enforced=true --namespace kube-system
</code></pre>
<ul>
<li>Open the web browser and browse secure Node port <a href="https://dashboard.traefik">https://dashboard.traefik</a>:&lt;NODE_PORT&gt;/ to access Traefik page securely<br>
<img class="img-fluid rounded" src="img/traefik1.png" alt=""></li>
<li>To learn more about helm traefik chart go <a href="https://github.com/helm/charts/tree/master/stable/traefik">here</a></li>
</ul>
<p>Thanks Happy Helming, do poke me for any problems</p>

          



<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
          <%@ include file="related-kube.jsp"%>
          
          <!-- Article Widget -->
         <%@ include file="related-linux.jsp"%>
         
           <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         <%@ include file="related-window-crypto.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>