<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="How to install drupal in kubernetes helm">
    <meta name="keywords" content="drupal in kubernetes helm, drupal kubernetes installaion, helm drupal install, drupal PersistentVolume, PersistentVolumeClaim, externel ip pending kubernetes, kubernetes tutorial, kubernetes by examples">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>How to install drupal in kubernetes helm</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/kube-drupal.jsp"
  },
  "name" : "How to install drupal in kubernetes helm",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Kubernetes drupal Installation (helm)",
  "image":"https://8gwifi.org/docs/img/kube-drupal.png",
  "datePublished" : "2019-01-25",
  "dateModified": "2019-01-25",
  "articleSection" : "Kubernetes drupal Installation (helm)",
  "articleBody" : [ "Introduction" ,"kubernetes Installation starts here", "First define the PersistentVolume drupal-pv where the drupal data to be stored. The hostPath tells the drupal directory is in /opt/drupal location" ,"Create PersistentVolume in kube cluster" ,"Define PersistentVolumeClaim drupal-pvc", "drupal Installation starts here, this is done through helm the kubernetes package manager"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Kubernetes drupal Installation (helm)</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Friday January 25, 2019</p>
          </p>
          
          <img class="img-fluid rounded" src="img/drupal2.png" height="400" width="500" alt="Referefce ">
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>

<h3 class="mt-4">Introduction </h3>
<p>In this article we will learn how to to setup <strong>drupal</strong> in kubernetes cluster using helm</p>
<p><a href="helm.sh">Helm</a>: Helm is a tool for managing Kubernetes charts. Charts are packages of pre-configured Kubernetes resources.</p>
<ul>
<li>Lets Begin deploying <strong>drupal</strong> using helm in <strong>kubernetes</strong> , if you are new to helm then download and initialize helm as follows</li>
</ul>
<pre><code class="language-console">root@kube-master:#  helm init
root@kube-master:# kubectl create serviceaccount --namespace kube-system tiller
root@kube-master:# kubectl create clusterrolebinding tiller-cluster-rule  --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
root@kube-master:#  kubectl patch deploy --namespace kube-system tiller-deploy  -p '{&quot;spec&quot;:{&quot;template&quot;:{&quot;spec&quot;:{&quot;serviceAccount&quot;:&quot;tiller&quot;}}}}'
</code></pre>
<ul>
<li>Make sure the title-deploy pod is up and running</li>
</ul>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl get pods -n kube-system 
NAME                                  READY     STATUS    RESTARTS   AGE
coredns-78fcdf6894-jvmlb              1/1       Running   0          1h
coredns-78fcdf6894-xstbn              1/1       Running   0          1h
etcd-kube-master                      1/1       Running   0          1h
kube-apiserver-kube-master            1/1       Running   0          1h
kube-controller-manager-kube-master   1/1       Running   0          1h
kube-flannel-ds-5gzn9                 1/1       Running   0          1h
kube-flannel-ds-tlc8j                 1/1       Running   0          1h
kube-proxy-kl4fg                      1/1       Running   0          1h
kube-proxy-krt6n                      1/1       Running   0          1h
kube-scheduler-kube-master            1/1       Running   0          1h
tiller-deploy-85744d9bfb-wh98g        1/1       Running   0          1h
</code></pre>
<ul>
<li>Once titler pod is up and running, deploying <strong>drupal</strong>  for this we need to go and create <strong>PersistentVolume</strong> and <strong>PersistentVolumeClaim</strong></li>
</ul>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>PersistentVolume</th>
<th>PersistentVolumeClaim</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr>
<td>drupal-mariadb-pv</td>
<td>drupal-mariadb-pvc</td>
<td>for storing drupal tables</td>
</tr>
<tr>
<td>drupal-data-pv</td>
<td>drupal-data-pvc</td>
<td>for storing druplaa files</td>
</tr>
<tr>
<td>drupal-apache-pv</td>
<td>helm will create for us</td>
<td>Apache files</td>
</tr>
</tbody>
</table>
<ul>
<li>Create <strong>drupal-mariadb-pv</strong> and <strong>drupal-mariadb-pvc</strong></li>
</ul>
<pre><code class="language-console">root@kube-master# echo &quot;
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mariadb-pv
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/
&quot; | kubectl apply -f -
</code></pre>
<p>The <strong>drupal-mariadb-pvc</strong></p>
<pre><code class="language-console">
root@kube-master# echo &quot;
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-drupal-mariadb-0
spec:
  storageClassName: &quot;&quot;
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
&quot; | kubectl apply -f -
</code></pre>
<ul>
<li>create <strong>drupal-data-pv</strong> and <strong>drupal-data-pvc</strong></li>
</ul>
<pre><code class="language-console">root@kube-master# echo &quot;
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-data-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/drupal
&quot; | kubectl apply -f -
</code></pre>
<p>The <strong>drupal-data-pvc</strong></p>
<pre><code class="language-console">root@kube-master# echo &quot;
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-drupal-drupal
spec:
  storageClassName: &quot;&quot;
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
&quot; | kubectl apply -f -
</code></pre>
<ul>
<li>Create <strong>drupal-apache-pv</strong></li>
</ul>
<pre><code class="language-console">root@kube-master# echo &quot;
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-drupal-drupal
spec:
  storageClassName: &quot;&quot;
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
&quot; | kubectl apply -f -
</code></pre>
<ul>
<li>Verify K8 pvc bounded to correct claims</li>
</ul>
<pre><code class="language-console">root@kube-master:# kubectl get pvc
NAME                    STATUS    VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-drupal-mariadb-0   Bound     drupal-mariadb-pv   4Gi        RWO,ROX                       18s
drupal-drupal-drupal    Bound     drupal-data-pv      1Gi        RWO,ROX                       10s
root@kube-master:# kubectl get pv
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                           STORAGECLASS   REASON    AGE
drupal-apache-pv    1Gi        RWO,ROX        Retain           Available                                                            7s
drupal-data-pv      1Gi        RWO,ROX        Retain           Bound       default/drupal-drupal-drupal                             15s
drupal-mariadb-pv   4Gi        RWO,ROX        Retain           Bound       default/data-drupal-mariadb-0                            21s
</code></pre>
<ul>
<li>Drupal Installation starts here, this is done through helm the kubernetes package manager,</li>
</ul>
<pre><code class="language-console">helm install --set drupalUsername=admin,drupalPassword=mydrupalpassword,mariadb.mariadbRootPassword=secretpassword,persistence.drupal.existingClaim=drupal-drupal-drupal,mariadb.enabled=true,master.persistence.existingClaim=data-drupal-mariadb-0 --name drupal stable/drupal

</code></pre>
<p>This will produce lot of useful resource  information related to DRUPAL</p>
<pre><code class="language-console">NAME:   drupal
LAST DEPLOYED: Fri Jan 25 16:25:21 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==&gt; v1/Pod(related)
NAME                            READY  STATUS             RESTARTS  AGE
drupal-drupal-7965fbcbb9-kp9v7  0/1    ContainerCreating  0         3s
drupal-mariadb-0                0/1    ContainerCreating  0         3s

==&gt; v1/Secret
NAME            TYPE    DATA  AGE
drupal-mariadb  Opaque  2     3s
drupal-drupal   Opaque  1     3s

==&gt; v1/ConfigMap
NAME                  DATA  AGE
drupal-mariadb        1     3s
drupal-mariadb-tests  1     3s

==&gt; v1/PersistentVolumeClaim
NAME                  STATUS  VOLUME            CAPACITY  ACCESS MODES  STORAGECLASS  AGE
drupal-drupal-apache  Bound   drupal-apache-pv  1Gi       RWO,ROX       3s

==&gt; v1/Service
NAME            TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)                     AGE
drupal-mariadb  ClusterIP     10.97.114.226   &lt;none&gt;       3306/TCP                    3s
drupal-drupal   LoadBalancer  10.103.184.148  &lt;pending&gt;    80:31127/TCP,443:31178/TCP  3s

==&gt; v1beta1/Deployment
NAME           DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
drupal-drupal  1        1        1           0          3s

==&gt; v1beta1/StatefulSet
NAME            DESIRED  CURRENT  AGE
drupal-mariadb  1        1        3s


NOTES:

*******************************************************************
*** PLEASE BE PATIENT: Drupal may take a few minutes to install ***
*******************************************************************

1. Get the Drupal URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w drupal-drupal'

  export SERVICE_IP=$(kubectl get svc --namespace default drupal-drupal --template &quot;{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}&quot;)
  echo &quot;Drupal URL: http://$SERVICE_IP/&quot;

2. Login with the following credentials

  echo Username: admin
  echo Password: $(kubectl get secret --namespace default drupal-drupal -o jsonpath=&quot;{.data.drupal-password}&quot; | base64 --decode)
</code></pre>
<ul>
<li>Once the <strong>drupal</strong> POD is up and running , your drupal is <strong>not</strong> ready to use Yet , you have to be <strong>patient</strong>, depend on your network speed, it will take further 3-4 minutes</li>
</ul>
<pre><code class="language-console">root@kube-master:# kubectl get pods
</code></pre>
<ul>
<li>To get your drupal admin password run</li>
</ul>
<pre><code class="language-console">root@kube-master:# kubectl get secret --namespace default drupal-drupal -o jsonpath=&quot;{.data.drupal-password}&quot; | base64 --decode
mydrupalpassword
</code></pre>
<ul>
<li>Verify the drupal service is up and running and external-ip column is no more pending</li>
</ul>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl get svc 
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
drupal-drupal    LoadBalancer   10.103.184.148   172.16.2.13   80:31127/TCP,443:31178/TCP   3m
drupal-mariadb   ClusterIP      10.97.114.226    &lt;none&gt;        3306/TCP                     3m
kubernetes       ClusterIP      10.96.0.1        &lt;none&gt;        443/TCP                      2d
</code></pre>
<ul>
<li>Open the web browser and browse your loadbalancer ip<br>
<img class="img-fluid rounded" src="img/drupal.png" alt="enter image description here"></li>
<li>Happy Helming and since its kubernetes you may encounter some issues, feel free to poke me</li>
</ul>


<hr>
<p><h2>Video Demo </h2> </p>
 <iframe width="420" height="315"
src="https://youtube.com/embed/LUcarJZcdIc">
</iframe> 

          



<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
          <%@ include file="related-kube.jsp"%>
          
          <!-- Article Widget -->
         <%@ include file="related-linux.jsp"%>
         
           <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         <%@ include file="related-window-crypto.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>