<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="RHEL8/Centos8 New Feature vs RHEL7/Centos7">
<meta name="keywords"content="rhel8 new feauture, whats new in centos8/rhel8, linux interview questions,sshfs mount">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>RHEL8/Centos8 New Feature vs RHEL7/Centos7</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/linux-8.jsp"
  },
  "name" : "RHEL8/Centos8 New Feature vs RHEL7/Centos7",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "RHEL8/Centos8 New Feature vs RHEL7/Centos7",
  "image":"https://8gwifi.org/docs/img/linux-8.png",
  "datePublished" : "2018-12-21",
  "dateModified": "2018-12-21",
  "articleSection" : "RHEL8/Centos8 New Feature vs RHEL7/Centos7",
  "articleBody" : [ "Application Streams","Repositories", "centos8 repo", "Software and Packages", "New Web Console ", "security", "Virtualization", "rhel8" , "nftables"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">RHEL8/Centos8 New Feature vs RHEL7/Centos7</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Monday October 21-2019</p>

				<hr>



				<img class="img-fluid rounded" src="img/linux-8.png"alt="Referefce 8gwifi.org">

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>

<p class="has-line-data" data-line-start="2" data-line-end="3"><strong>TL;DR</strong></p>
<p class="has-line-data" data-line-start="4" data-line-end="5">The RHEL8 releases on 8.0 / May 7, 2019; 5 months ago. <strong>Red Hat Enterprise Linux 8 (Ootpa)</strong> is based on <strong>Fedora 28</strong>, upstream Linux kernel 4.18, GCC 8.2, glibc 2.28, systemd 239, and GNOME 3.28</p>
<p class="has-line-data" data-line-start="6" data-line-end="7">The  CentOS-8 (1905) release platform derived from the sources of Red Hat Enterprise Linux (RHEL)</p>
<p class="has-line-data" data-line-start="8" data-line-end="9">Here are the some Notable Changes to latest Release.</p>
<h2 class="code-line" data-line-start=10 data-line-end=11 ><a id="Application_Streams_10"></a>Application Streams</h2>
<p class="has-line-data" data-line-start="12" data-line-end="13">RHEL 8.0/Centos8  introduces the concept of Application Streams. Each application stream will be supported from two to five years.</p>
<p class="has-line-data" data-line-start="14" data-line-end="15">Application streams are fully supported for a predefined lifetime for example</p>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>Application Stream</th>
<th>Release Date</th>
<th>Retirement Date</th>
<th>Release</th>
</tr>
</thead>
<tbody>
<tr>
<td>varnish 6</td>
<td>May 2019</td>
<td>May 2022</td>
<td>8.0.0</td>
</tr>
<tr>
<td>postgresql 10</td>
<td>May 2019</td>
<td>May 2024</td>
<td>8.0.0.</td>
</tr>
<tr>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>
</tbody>
</table>
<h2 class="code-line" data-line-start=22 data-line-end=23 ><a id="Repositories_22"></a>Repositories</h2>
<p class="has-line-data" data-line-start="24" data-line-end="25">Red Hat Enterprise Linux 8 is distributed through two main repositories and introduce <strong>Red Hat Universal Base Image (UBI).</strong></p>
<ul>
<li class="has-line-data" data-line-start="26" data-line-end="27">BaseOS</li>
<li class="has-line-data" data-line-start="27" data-line-end="28">AppStream</li>
</ul>
<p class="has-line-data" data-line-start="30" data-line-end="31">Both repositories are required for a basic RHEL installation, and are available with all RHEL subscriptions.</p>
<ul>
<li class="has-line-data" data-line-start="32" data-line-end="33">RHEL8</li>
</ul>
<pre><code class="html">sh-4.4# dnf repolist
ubi-8-appstream    Red Hat Universal Base Image 8 (RPMs) - AppStream   778
ubi-8-baseos       Red Hat Universal Base Image 8 (RPMs) - BaseOS      659
</code></pre>
<ul>
<li class="has-line-data" data-line-start="39" data-line-end="40">Centos 8</li>
</ul>
<pre><code class="html">sh-4.4# dnf repolist
Last metadata expiration check: 0:08:52 ago on Sun Oct 20 11:54:48 2019.
repo id  repo name  status
AppStream  CentOS-8 - AppStream 5069
BaseOS CentOS-8 - Base  2835
extras CentOS-8 - Extras 3

</code></pre>
<h2 class="code-line" data-line-start=52 data-line-end=53 ><a id="Software_and_Packages_52"></a>Software and Packages</h2>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>Package</th>
<th>RHEL8/Centos8</th>
<th>RHEL7/Centos7</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>YUM</strong></td>
<td><strong>YUM v4</strong>: Based on <strong>DNF</strong> technology</td>
<td><strong>YUM v3</strong> used on RHEL 7/Centos7</td>
</tr>
<tr>
<td><strong>Shells and command-line tools</strong></td>
<td><strong>The  <code>nobody</code>  user replaces  <code>nfsnobody</code></strong></td>
<td>he <code>nobody</code> user and group pair with the ID of 99 and the <code>nfsnobody</code> user and group pair with the ID of 65534,</td>
</tr>
<tr>
<td><strong>version control systems</strong></td>
<td><code>Git 2.18</code>, <code>Mercurial 4.8</code>, and <code>Subversion 1.10</code>  and Concurrent Versions System (CVS) and Revision Control System (RCS), available in RHEL 7, are not distributed with RHEL 8</td>
<td>Older versions</td>
</tr>
<tr>
<td><strong>Python</strong></td>
<td><strong><code>Python 3</code>  is the default  <code>Python</code></strong></td>
<td><strong><code>Python 2.7</code>  is the default  <code>Python</code></strong></td>
</tr>
<tr>
<td><strong>PHP</strong></td>
<td>distributed with <code>PHP 7.2</code></td>
<td>distributed with <code>PHP 5.4</code></td>
</tr>
<tr>
<td><strong>Nodejs</strong></td>
<td><strong><code>Node.js</code>  new in RHEL8</strong></td>
<td>NA</td>
</tr>
<tr>
<td><strong>Perl</strong></td>
<td>Perl 5.26</td>
<td>Perl 5.20</td>
</tr>
<tr>
<td><strong>httpd</strong></td>
<td>Apache HTTP Server 2.4.37</td>
<td></td>
</tr>
<tr>
<td><strong>nginx</strong></td>
<td>RHEL 8 introduces <code>nginx 1.14</code></td>
<td>NA</td>
</tr>
<tr>
<td><strong>Database</strong></td>
<td>MySQL 8.0, MariaDB 10.3,PostgreSQL 10 Redis 5. <code>MongoDB</code> database server is not included in RHEL 8.0</td>
<td>-</td>
</tr>
<tr>
<td><strong>squid</strong></td>
<td>Squid 4.4</td>
<td>Older version of squid</td>
</tr>
<tr>
<td><strong>Varnish</strong></td>
<td><strong><code>Varnish Cache</code>  new in RHEL</strong> Varnish Cache 6.0</td>
<td>NA</td>
</tr>
</tbody>
</table>
<h2 class="code-line" data-line-start=69 data-line-end=70 ><a id="New_Web_Console_69"></a>New Web Console</h2>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>webconsole</th>
<th>RHEL8</th>
<th>RHEL7</th>
</tr>
</thead>
<tbody>
<tr>
<td>Subscriptions</td>
<td>The web console's Subscriptions page is now provided by the new <code>subscription-manager-cockpit</code> package.</td>
<td>opensource</td>
</tr>
<tr>
<td><strong>firewall</strong></td>
<td>The <strong>Networking</strong> page in the RHEL 8 web console now includes a <strong>Firewall</strong> section</td>
<td>NA</td>
</tr>
<tr>
<td>Virtual Machine</td>
<td>The <code>Virtual Machines</code> page can now be added to the RHEL 8 web console interface, which enables the user to create and manage libvirt-based virtual machines</td>
<td>NA</td>
</tr>
</tbody>
</table>
<h2 class="code-line" data-line-start=76 data-line-end=77 ><a id="Security_76"></a>Security</h2>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>Firewall</th>
<th>RHEL8/Centos8</th>
<th>RHEL7/Centos7</th>
</tr>
</thead>
<tbody>
<tr>
<td>nftables</td>
<td><strong><code>nftables</code></strong>  replaces <code>iptables</code>, <code>ip6tables</code>, <code>ebtables</code> and <code>arptables</code>  as the default network packet filtering framework</td>
<td>iptables is default</td>
</tr>
<tr>
<td>firewalld</td>
<td><strong><code>firewalld</code>  uses  <code>nftables</code>  by default</strong></td>
<td>-</td>
</tr>
</tbody>
</table>
<h2 class="code-line" data-line-start=83 data-line-end=84 ><a id="Virtualization_83"></a>Virtualization</h2>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>Virtualization</th>
<th>RHEL8/Centos8</th>
<th>RHEL7</th>
</tr>
</thead>
<tbody>
<tr>
<td>Virtualization</td>
<td><code>qemu-kvm</code> 2.12</td>
<td><code>qemu-kvm</code> 1.5.3</td>
</tr>
</tbody>
</table>
<h2 class="code-line" data-line-start=90 data-line-end=91 ><a id="References_90"></a>References</h2>
<ul>
<li class="has-line-data" data-line-start="92" data-line-end="94">
<p class="has-line-data" data-line-start="92" data-line-end="93"><a href="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#architectures">RHEL8 Release Note</a></p>
</li>
<li class="has-line-data" data-line-start="94" data-line-end="95">
<p class="has-line-data" data-line-start="94" data-line-end="95"><a href="https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.1905">Centos8 Release Note</a></p>
</li>
</ul>

				<p>
					Next Reading : <a href="linux-monitor-commands.jsp">How to
						Monitoring All Executed Commands in Linux </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>