<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="How to set up a LAMP stack on Centos8 / RHEL 8">
<meta name="keywords"content="How to set up a LAMP stack on Centos8 / RHEL 8, enable php-fpm on lamp stack, linux interview questions,sshfs mount">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>How to set up a LAMP stack on Centos8 / RHEL 8</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/linux-lamp.jsp"
  },
  "name" : "How to set up a LAMP stack on Centos8 / RHEL 8",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "How to set up a LAMP stack on Centos8 / RHEL 8",
  "image":"https://8gwifi.org/docs/img/linux-lamp.png",
  "datePublished" : "2019-10-30",
  "dateModified": "2019-10-30",
  "articleSection" : "How to set up a LAMP stack on Centos8 / RHEL 8",
  "articleBody" : [ "lamp stack install on centos8","lamp stack install on rhel8", "php7", "Software and Packages", "New Web Console ", "security", "Virtualization", "rhel8" , "nftables"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">How to set up a LAMP stack on Centos8 / RHEL 8</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Wednesday October 30-2019</p>

				<hr>



				<img class="img-fluid rounded" src="img/linux-lamp.png"alt="Referefce 8gwifi.org">

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>

<p class="has-line-data" data-line-start="3" data-line-end="4">In this tutorial we will install LAMP on Centos8 with FPM enabled. Here are the listed LAMP component which is going to be installed.</p>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>Application</th>
<th>Version</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>httpd</td>
<td>2.4.37</td>
<td>Base Apache</td>
</tr>
<tr>
<td>mod_ssl &amp; openssl</td>
<td><strong>openssl</strong>-1.1.1</td>
<td>For TLS processing</td>
</tr>
<tr>
<td>mariadb-server &amp; mariadb</td>
<td>10.3.11</td>
<td>The Database Server</td>
</tr>
<tr>
<td>php</td>
<td>7.2.11</td>
<td>Base PHP</td>
</tr>
<tr>
<td>php-mysqlnd</td>
<td>7.2.11</td>
<td>PHP MySQL Library</td>
</tr>
<tr>
<td>php-fpm</td>
<td>7.2.11</td>
<td>FPM (FastCGI Process Manager)</td>
</tr>
<tr>
<td>php-xml</td>
<td>7.2.11</td>
<td>PHP  SimpleXML Parser</td>
</tr>
<tr>
<td>php-mbstring</td>
<td>7.2.11</td>
<td>PHP Multibyte String</td>
</tr>
</tbody>
</table>
<ol>
<li class="has-line-data" data-line-start="17" data-line-end="18">Update System first</li>
</ol>
<pre><code class="html">dnf -y update
</code></pre>
<ol start="2">
<li class="has-line-data" data-line-start="22" data-line-end="24">Install Helper APP</li>
</ol>
<pre><code class="html">dnf -y install nano curl wget bind-utils 
</code></pre>
<ol start="3">
<li class="has-line-data" data-line-start="29" data-line-end="31">Install LAMP with MariaDB</li>
</ol>
<pre><code class="html">dnf -y install mariadb-server mariadb php php-fpm php-xml php-json php-mysqlnd php-mbstring php-opcache php-gd php-cli firewalld mod_ssl
</code></pre>
<ol start="4">
<li class="has-line-data" data-line-start="36" data-line-end="38">Enable Load on Startup for <code>httpd</code>  <code>MariaDB</code> and <code>PHP-FPM</code></li>
</ol>
<pre><code class="html">systemctl enable httpd.service
systemctl enable php-fpm.service
systemctl enable mariadb.service
</code></pre>
<ol start="5">
<li class="has-line-data" data-line-start="45" data-line-end="46">Configure Firewalld and Allow HTTP/HTTPS</li>
</ol>
<pre><code class="html">firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload
</code></pre>
<ol start="6">
<li class="has-line-data" data-line-start="52" data-line-end="53">Create simple PHP Info page to verify PHP is working in Apache in the <code>/var/www/html/info.php</code></li>
</ol>
<pre><code class="html">&lt;?php

phpinfo();
</code></pre>
<ol start="7">
<li class="has-line-data" data-line-start="59" data-line-end="61">Fix the File permissions to purely configured as Non-Root User</li>
</ol>
<pre><code class="html">chown -R apache:apache /etc/run/
chown -R apache:apache /var/www
chown -R apache:apache /etc/httpd 
</code></pre>
<ol start="8">
<li class="has-line-data" data-line-start="67" data-line-end="69">Start the Apache httpd server</li>
</ol>
<pre><code class="html">systemctl start httpd.service
systemctl status httpd
</code></pre>
<ol start="9">
<li class="has-line-data" data-line-start="74" data-line-end="76">Test It</li>
</ol>
<pre><code class="html"># curl -I  http://localhost/        
HTTP/1.1 200 OK
Date: Wed, 30 Oct 2019 05:20:02 GMT
Server: Apache/2.4.37 (centos) OpenSSL/1.1.1
Last-Modified: Wed, 30 Oct 2019 05:16:20 GMT
ETag: &quot;69-59619d551e9d9&quot;
Accept-Ranges: bytes
Content-Length: 105
</code></pre>
<p class="has-line-data" data-line-start="87" data-line-end="88"><img class="img-fluid rounded" src="img/phpinfo.png" alt="PHP Info "></p>
<p class="has-line-data" data-line-start="89" data-line-end="90">You can also run the following command to list installed modules only:</p>
<pre><code class="html">php -m
</code></pre>
<ol start="10">
<li class="has-line-data" data-line-start="95" data-line-end="97">Start &amp; Configure MariaDB</li>
</ol>
<pre><code class="html">systemctl start mariadb.service
systemctl status mariadb
</code></pre>
<p class="has-line-data" data-line-start="102" data-line-end="103">Once MariaDB is started, complete the series of questions likeHow to Secure MariaDB by setting root password</p>
<pre><code class="html">/usr/bin/mysql_secure_installation
</code></pre>

<p><h3>Video Demo </h3> </p>
 <iframe width="420" height="315"
src="https://youtube.com/embed/oLIz9uE19ws">
</iframe> 



<p class="has-line-data" data-line-start="107" data-line-end="108"><strong>That's ALL  (Nope )</strong></p>

				<p>
					Next Reading : <a href="linux-monitor-commands.jsp">How to
						Monitoring All Executed Commands in Linux </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>