<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Detecting Linux distribution name and version">
<meta name="keywords"content="Detecting Linux distribution name and version , linux interview questions">
<meta name="author" content="Anish nath">
<meta name="robots" content="index,follow" />
<meta name="googlebot" content="index,follow" />
<meta name="resource-type" content="document" />
<meta name="classification" content="tools" />
<meta name="language" content="en" />

<title>How to detect linux os version</title>

<!-- Bootstrap core CSS -->
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="css/blog-post.css" rel="stylesheet">

<link rel="stylesheet" href="css/highlight/default.min.css">
<script src="css/highlight/highlight.min.js"></script>
<script>
	hljs.initHighlightingOnLoad();
</script>


<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/linux-detectos.jsp"
  },
  "name" : "Detecting Linux distribution name and version",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Detecting Linux distribution name and version",
  "image":"https://8gwifi.org/docs/img/linux-detectos.png",
  "datePublished" : "2019-05-05",
  "dateModified": "2019-05-05",
  "articleSection" : "Detecting Linux distribution name and version",
  "articleBody" : [ "cat /etc/release","lsb_release", "/etc/os-release", "/etc/*release"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


</head>

<body>

	<!-- Navigation -->
	<%@ include file="navigation.jsp"%>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Title -->
				<h1 class="mt-4">Detecting Linux distribution name and version</h1>

				<!-- Author -->
				<p class="lead">
					by <a href="https://www.linkedin.com/in/anishnath">Anish</a>
				</p>

				<hr>

				<!-- Date/Time -->
				<p>Posted on Sunday May 5th</p>

				<hr>



				<img class="img-fluid rounded" src="img/linux-detectos.png"alt="Referefce 8gwifi.org"> 

				<%@ include file="footer_adsense.jsp"%>
				<%@ include file="analytics.jsp"%>

				<hr>
					<p>Just execute <code>lsb_release -a</code></p>
<pre><code class="html">bash ~ lsb_release -a
No LSB modules are available.
Distributor ID:  Ubuntu
Description:  Ubuntu 16.04.4 LTS
Release:  16.04
Codename:  xenial
</code></pre>
<p>if the <code>lsb_release</code> is not available then</p>
<pre><code class="html">bash ~ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l
</code></pre>
<p>Or Look at <code>/etc/os-release</code></p>
<pre><code class="html">bash ~ cat /etc/os-release 
NAME=&quot;Ubuntu&quot;
VERSION=&quot;16.04.4 LTS (Xenial Xerus)&quot;
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME=&quot;Ubuntu 16.04.4 LTS&quot;
VERSION_ID=&quot;16.04&quot;
HOME_URL=&quot;http://www.ubuntu.com/&quot;
SUPPORT_URL=&quot;http://help.ubuntu.com/&quot;
BUG_REPORT_URL=&quot;http://bugs.launchpad.net/ubuntu/&quot;
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
</code></pre>
<p>Or you can try <code>cat /etc/*release</code></p>
<pre><code class="html">bash ~ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION=&quot;Ubuntu 16.04.4 LTS&quot;
NAME=&quot;Ubuntu&quot;
VERSION=&quot;16.04.4 LTS (Xenial Xerus)&quot;
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME=&quot;Ubuntu 16.04.4 LTS&quot;
VERSION_ID=&quot;16.04&quot;
HOME_URL=&quot;http://www.ubuntu.com/&quot;
SUPPORT_URL=&quot;http://help.ubuntu.com/&quot;
BUG_REPORT_URL=&quot;http://bugs.launchpad.net/ubuntu/&quot;
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
</code></pre>
<p>For fedora like system look at <code>/etc/redhat-release</code></p>
<pre><code class="html">$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.7 (Santiago)
</code></pre>
<p>execute <code>uname -a</code> to get basic information about the Linux Kernel</p>
<pre><code class="html">bash ~ uname -a 
Linux provisoner 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
</code></pre>
<p>Showing kernel Information <code>el6</code> architecture <code>x86_64</code></p>
<pre><code class="html">$ uname -a 
Linux my-rhel 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
</code></pre>
<p>As per man page here few more options for uname</p>
<pre><code class="html">-a, --all                         print all information, 
-s, --kernel-name       print the kernel name
-n, --nodename          print the network node hostname
-r, --kernel-release     print the kernel release
-v, --kernel-version    print the kernel version
-m, --machine            print the machine hardware name
-p, --processor           print the processor type (non-portable)
-i, --hardware-platform print the hardware platform (non-portable)
-o, --operating-system  print the operating system
</code></pre>

				<p>
					Next Reading : <a href="linux-monitor-commands.jsp">How to
						Monitoring All Executed Commands in Linux </a>
				</p>

				<hr>
				<%@ include file="thanks.jsp"%>
				<!-- Comments Form -->


				<!-- Single Comment -->


				<!-- Comment with nested comments -->


			</div>

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">

				<!-- Ad Widget -->
				<%@ include file="footer_adsense.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-linux.jsp"%>

				<!-- Article Widget -->
				<%@ include file="related-ansible.jsp"%>

				<%@ include file="related-kube.jsp"%>

				<%@ include file="related-openstack.jsp"%>

				<%@ include file="related-cryptography.jsp"%>
				<%@ include file="related-window-crypto.jsp"%>




				<!-- Topic Widget -->
				<%@ include file="side.jsp"%>

			</div>

		</div>
		<!-- /.row -->
		<%@ include file="addcomments.jsp"%>

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org
				2018</p>
		</div>
		<!-- /.container -->
	</footer>

	 <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>