<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Openstack Client Installation, pip installation of openstack client">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>Openstack Client Installation </title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/"
  },
  "name" : "Install the OpenStack command-line clients on Centos/Rhel/Fedora Like System",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Install the OpenStack command-line clients on Centos/Rhel/Fedora Like System",
  "image":"https://8gwifi.org/docs/img/openstack_client.jpg",
  "datePublished" : "2018-06-25",
  "dateModified": "2018-06-25",
  "articleSection" : "Openstack client Installation",
  "articleBody" : [ "Install the prerequisite software", "Install the python-openstackclient", "Source the project credentials </STRONG> to gain access to project-only CLI commands:", "Verify Openstack </STRONG> client operation", "if you need to install an individual client project, replace the <STRONG>PROJECT</STRONG> name in this pip install command using the list below." ],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Install the OpenStack command-line clients on Centos/Rhel/Fedora Like System </h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on Monday June 25</p>

          <hr>

        
          <!-- Preview Image 
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
          -->
           <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>

          <hr>

          <!-- Post Content -->
          <p class="lead">Openstack client Installation</p>

          <p><strong>Install the prerequisite software</strong></p>
		  <pre><code class="html">sudo yum install python-devel python-pip gcc
sudo python -m pip install --upgrade pip setuptools wheel
sudo pip install --upgrade pip</code></pre>

		  <p><strong>Install the python-openstackclient</strong></p>
		  
		  <pre><code class="html">sudo pip install python-openstackclient</code></pre>

          <p><strong>Source the project credentials </strong> to gain access to project-only CLI commands:</p>
          <pre><code class="html">. project-openrc
Please enter your OpenStack Password for project security-ops as user orchestration: </code></pre>
          
          <p> <strong>Verify Openstack </strong> client operation  </p>
          <pre><code class="html"># openstack image list </code></pre>
          <pre><code class="html">+--------------------------------------+-------------------------------+--------+
| ID                                   | Name                          | Status |
+--------------------------------------+-------------------------------+--------+
| 8758f8c4-f83b-4ecf-b833-9b6962bd894a | centos-7                      | active |
| 759c7687-6a42-4694-b4a9-94185c0491e0 | rhel-workstation-7.3          | active |
| 51ee39ec-5daf-4af1-b023-71a1b24e7807 | rhel7-server-production       | active |
| dbd72450-477d-43df-9d0c-d7c719bc6833 | rhel7-workstation             | active |
| d0550c02-cb90-4f0c-98a1-809dd1d50f19 | rhel7-workstation-snapshot    | active |
+--------------------------------------+-------------------------------+--------+</code></pre>
<hr>
<p> if you need to install an individual client project, replace the <strong>PROJECT</strong> name in this pip install command using the list below.</p>
<pre><code class="html">pip install python-PROJECTclient</code></pre>

<p> For example </p>
<p> Installing <strong> barbican </strong>- Key Manager Service API </p>
<pre><code class="html">pip install python-barbican</code></pre>

<p> Simillarly Other Client can be Installed </p>
<ul class="list-group">
 <li class="list-group-item"><b>ceilometer </b>- Telemetry API </li>
 <li class="list-group-item"><b>cinder</b> - Block Storage API and extensions</li>
 <li class="list-group-item"><b>cloudkitty</b> - Rating service API</li>
 <li class="list-group-item"><b>designate</b> - DNS service API</li>
 <li class="list-group-item"><b>fuel</b> - Deployment service API</li>
 <li class="list-group-item"><b>glance</b> - Image service API</li>
 <li class="list-group-item"><b>gnocchi</b> - Telemetry API v3</li>
 <li class="list-group-item"><b>heat</b> - Orchestration API</li>
 <li class="list-group-item"><b>magnum</b> - Container Infrastructure Management service API</li>
 <li class="list-group-item"><b>manila</b> - Shared file systems API</li>
 <li class="list-group-item"><b>mistral</b> - Workflow service API</li>
 <li class="list-group-item"><b>monasca</b> - Monitoring API</li>
 <li class="list-group-item"><b>murano</b> - Application catalog API</li>
 <li class="list-group-item"><b>neutron</b> - Networking API</li>
 <li class="list-group-item"><b>nova</b> - Compute API and extensions</li>
 <li class="list-group-item"><b>sahara</b> - Data Processing API</li>
 <li class="list-group-item"><b>senlin</b> - Clustering service API</li>
 <li class="list-group-item"><b>swift</b> - Object Storage API</li>
 <li class="list-group-item"><b>trove</b> - Database service API</li>
</ul>



      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
          

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          <!-- Categories Widget -->
         <%@ include file="related-openstack.jsp"%>
         
          <!-- Side Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         <%@ include file="addcomments.jsp"%>
         

        </div>

      </div>
      <!-- /.row -->
      <%@ include file="addcomments.jsp"%>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>