<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="php openssl tutorial on openssl_get_curve_names php openssl_get_curve_names example, php openssl functions, php get all ec curvenames, openssl ec curve names">
    <meta name="keywords" content="openssl_get_curve_names php openssl_get_curve_names example, php cryptography topics, php security, php interview questions, php openssl functions, php book,php get all ec curvenames, openssl ec curve names">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>php openssl tutorial on openssl_get_curve_names</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/php-eccurvenames.jsp"
  },
  "name" : "php get all ec curve names",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "php openssl tutorial on openssl_get_curve_names",
  "image":"https://8gwifi.org/docs/img/php/php-eccurvenames.png",
  "datePublished" : "2018-12-12",
  "dateModified": "2018-12-12",
  "articleSection" : "php openssl tutorial on openssl_get_curve_names",
  "articleBody" : [ "php openssl example ", "php openssl_get_curve_names" , "php openssl functions", "php cryptography", "openssl get eccurve names" , "get all ec curve names in php"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">php openssl_get_curve_names example</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Wednesday December 12 , 2018</p>
          </p>
          
          
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          
          <hr>
<h2><a id="EC_Curve_Names_0"></a>EC Curve Names</h2>
<p>php openssl function <strong>openssl_get_curve_names</strong>: Gets list of available curve names for ECC</p>
<ul>
<li>Supported PHP Versions (<strong>PHP 7 &gt;= 7.1.0</strong>)</li>
</ul>
<p>The Syntax</p>

<pre><code class="language-php"><span class="hljs-keyword">array</span>  openssl_get_curve_names ( void )
</code></pre>
<p>Gets the list of available curve names for use in Elliptic curve cryptography (ECC) for public/private key operations. The two most widely standardized/supported curves are <em>prime256v1</em> (NIST P-256) and <em>secp384r1</em> (NIST P-384).</p>
<p>Elliptic curve based algorithms use significantly smaller key sizes than their non elliptic curve equivalents.</p>
<p>The approximate equivalence in security strength for symmetric algorithms compared to standard asymmetric algorithms and elliptic curve algorithms is shown in the table below.</p>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th>AES Symmetric Keysize (Bits)</th>
<th>RSA and DSA Keysize (Bits)</th>
<th>ECC Keysize (Bits)</th>
</tr>
</thead>
<tbody>
<tr>
<td>80</td>
<td>1024</td>
<td>160</td>
</tr>
<tr>
<td>112</td>
<td>2048</td>
<td>224</td>
</tr>
<tr>
<td>128</td>
<td>3072</td>
<td>256</td>
</tr>
<tr>
<td>192</td>
<td>7680</td>
<td>384</td>
</tr>
<tr>
<td>256</td>
<td>15360</td>
<td>512</td>
</tr>
</tbody>
</table>
<p><a href="http://dx.doi.org/10.6028/NIST.SP.800-57pt1r4">NIST recommends using ECC curves with at least 256 bits</a>.</p>
<p><strong>Examples</strong></p>
<p><strong>openssl_get_curve_names() example</strong> Gets the list of available curve names for use in Elliptic curve cryptography (ECC)</p>

<pre><code class="language-php"><span class="hljs-preprocessor">&lt;?php</span>  
<span class="hljs-comment">/**  
 * Created by https://8gwifi.org  
  * User: Anish Nath  
 * Date: 2018-12-12 * Time: 10:40 */</span>  
<span class="hljs-variable">$curvenames</span> = openssl_get_curve_names();  
print_r(<span class="hljs-variable">$curvenames</span>);  
  
<span class="hljs-preprocessor">?&gt;</span>
</code></pre>
<p>The above example will output something similar to:</p>

<pre><code class="language-console">$ /usr/bin/php get_get_curve_names.php
Array
(
    [0] =&gt; secp112r1
    [1] =&gt; secp112r2
    [2] =&gt; secp128r1
    [3] =&gt; secp128r2
    [4] =&gt; secp160k1
    [5] =&gt; secp160r1
    [6] =&gt; secp160r2
    [7] =&gt; secp192k1
    [8] =&gt; secp224k1
    [9] =&gt; secp224r1
    [10] =&gt; secp256k1
    [11] =&gt; secp384r1
    [12] =&gt; secp521r1
    [13] =&gt; prime192v1
    [14] =&gt; prime192v2
    [15] =&gt; prime192v3
    [16] =&gt; prime239v1
    [17] =&gt; prime239v2
    [18] =&gt; prime239v3
    [19] =&gt; prime256v1
    [20] =&gt; sect113r1
    [21] =&gt; sect113r2
    [22] =&gt; sect131r1
    [23] =&gt; sect131r2
    [24] =&gt; sect163k1
    [25] =&gt; sect163r1
    [26] =&gt; sect163r2
    [27] =&gt; sect193r1
    [28] =&gt; sect193r2
    [29] =&gt; sect233k1
    [30] =&gt; sect233r1
    [31] =&gt; sect239k1
    [32] =&gt; sect283k1
    [33] =&gt; sect283r1
    [34] =&gt; sect409k1
    [35] =&gt; sect409r1
    [36] =&gt; sect571k1
    [37] =&gt; sect571r1
    [38] =&gt; c2pnb163v1
    [39] =&gt; c2pnb163v2
    [40] =&gt; c2pnb163v3
    [41] =&gt; c2pnb176v1
    [42] =&gt; c2tnb191v1
    [43] =&gt; c2tnb191v2
    [44] =&gt; c2tnb191v3
    [45] =&gt; c2pnb208w1
    [46] =&gt; c2tnb239v1
    [47] =&gt; c2tnb239v2
    [48] =&gt; c2tnb239v3
    [49] =&gt; c2pnb272w1
    [50] =&gt; c2pnb304w1
    [51] =&gt; c2tnb359v1
    [52] =&gt; c2pnb368w1
    [53] =&gt; c2tnb431r1
    [54] =&gt; wap-wsg-idm-ecid-wtls1
    [55] =&gt; wap-wsg-idm-ecid-wtls3
    [56] =&gt; wap-wsg-idm-ecid-wtls4
    [57] =&gt; wap-wsg-idm-ecid-wtls5
    [58] =&gt; wap-wsg-idm-ecid-wtls6
    [59] =&gt; wap-wsg-idm-ecid-wtls7
    [60] =&gt; wap-wsg-idm-ecid-wtls8
    [61] =&gt; wap-wsg-idm-ecid-wtls9
    [62] =&gt; wap-wsg-idm-ecid-wtls10
    [63] =&gt; wap-wsg-idm-ecid-wtls11
    [64] =&gt; wap-wsg-idm-ecid-wtls12
    [65] =&gt; Oakley-EC2N-3
    [66] =&gt; Oakley-EC2N-4
    [67] =&gt; brainpoolP160r1
    [68] =&gt; brainpoolP160t1
    [69] =&gt; brainpoolP192r1
    [70] =&gt; brainpoolP192t1
    [71] =&gt; brainpoolP224r1
    [72] =&gt; brainpoolP224t1
    [73] =&gt; brainpoolP256r1
    [74] =&gt; brainpoolP256t1
    [75] =&gt; brainpoolP320r1
    [76] =&gt; brainpoolP320t1
    [77] =&gt; brainpoolP384r1
    [78] =&gt; brainpoolP384t1
    [79] =&gt; brainpoolP512r1
    [80] =&gt; brainpoolP512t1
)
</code></pre>
<p>In <code>openssl</code> You can get a list of available ec curve name by calling</p>

<pre><code class="language-console">$ openssl ecparam -list_curves
</code></pre>
<p>The above example will output something similar to:</p>

<pre><code class="language-console">secp112r1 : SECG/WTLS curve over a 112 bit prime field
secp112r2 : SECG curve over a 112 bit prime field
secp128r1 : SECG curve over a 128 bit prime field
secp128r2 : SECG curve over a 128 bit prime field
secp160k1 : SECG curve over a 160 bit prime field
secp160r1 : SECG curve over a 160 bit prime field
......
......
</code></pre>
<p>Continue Reading <a href="php-asym.jsp#Generate_EC_Key_Pair_193">how to generate ec key pair</a></p>
<p><a href="https://8gwifi.org/ecsignverify.jsp">Generate EC Curve Online Sign Verify Message</a></p>

<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="addcomments.jsp"%>
      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 
         
         
         <%@ include file="related-go.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         
         <%@ include file="related-window-crypto.jsp"%>

		 
          <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         <%@ include file="related-linux.jsp"%>
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>


      </div>
      
      <!-- /.row -->

    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>