<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="php openssl tutorial on openssl_get_md_methods, php openssl_get_md_methods example, php openssl functions">
    <meta name="keywords" content="openssl list-cipher-commands openssl_get_md_methods, php openssl_get_md_methods example, php cryptography topics, php security, php interview questions, php openssl functions, php book">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>php openssl tutorial on openssl_get_md_methods</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/php-digestmethod.jsp"
  },
  "name" : "go lang encoding decoding",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "php openssl tutorial on openssl_get_md_method",
  "image":"https://8gwifi.org/docs/img/php/php-digestmethod.png",
  "datePublished" : "2018-12-12",
  "dateModified": "2018-12-12",
  "articleSection" : "php openssl tutorial on openssl_get_md_method",
  "articleBody" : [ "php openssl example ", "php openssl_get_md_method" , "php openssl functions", "php cryptography"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">php openssl_get_md_method example</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Wednesday December 12 , 2018</p>
          </p>
          
          
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          
          <hr>
<h2><a id="openssl_get_md_methods_0"></a>openssl_get_md_methods</h2>
<p><strong>openssl_get_md_method</strong>: Gets available digest methods.</p>
<ul>
<li>Supported PHP Versions (<strong>PHP 5 &gt;= 5.3.0, PHP 7</strong>)</li>
</ul>
<p>The Syntax</p>
<p></p>
<pre><code class="language-php"><span class="hljs-keyword">array</span>  openssl_get_md_methods ([ bool  <span class="hljs-variable">$aliases</span> =  `<span class="hljs-keyword">FALSE</span>` ] )
</code></pre>
<ul>
<li><strong>aliases</strong>: Set to TRUE if cipher aliases should be included within the returned array.</li>
<li><strong>Returns</strong> An <a href="http://php.net/manual/en/language.types.array.php">array</a> of available digest methods.</li>
</ul>
<p><strong>Examples</strong></p>
<p><strong>openssl_get_md_methods()</strong>  example  Shows how the available digest might look, and also which aliases might be available.</p>
<p></p>
<pre><code class="language-php"><span class="hljs-preprocessor">&lt;?php</span>  
<span class="hljs-comment">/**  
 * Created by https://8gwifi.org  
 * User: Anish Nath  
 * Date: 2018-12-12 * Time: 10:40 
 * */</span>  
<span class="hljs-variable">$digests</span> = openssl_get_md_methods();  
<span class="hljs-variable">$digests_and_aliases</span> = openssl_get_md_methods(<span class="hljs-keyword">true</span>);  
<span class="hljs-variable">$digest_aliases</span> = array_diff(<span class="hljs-variable">$digests_and_aliases</span>, <span class="hljs-variable">$digests</span>);  
print_r(<span class="hljs-variable">$digests</span>);  
print_r(<span class="hljs-variable">$digest_aliases</span>);  
<span class="hljs-preprocessor">?&gt;</span>
</code></pre>
<p>The above example will output something similar to:</p>
<p></p>
<pre><code class="language-console">$ /usr/bin/php get_md_methods.php
Array
(
    [0] =&gt; DSA
    [1] =&gt; DSA-SHA
    [2] =&gt; GOST 28147-89 MAC
    [3] =&gt; GOST R 34-11-2012 (512 bit)
    [4] =&gt; GOST R 34.11-2012 (256 bit)
    [5] =&gt; GOST R 34.11-94
    [6] =&gt; MD4
    [7] =&gt; MD5
    [8] =&gt; RIPEMD160
    [9] =&gt; SHA
    [10] =&gt; SHA1
    [11] =&gt; SHA224
    [12] =&gt; SHA256
    [13] =&gt; SHA384
    [14] =&gt; SHA512
    [15] =&gt; dsaEncryption
    [16] =&gt; dsaWithSHA
    [17] =&gt; ecdsa-with-SHA1
    [18] =&gt; gost-mac
    [19] =&gt; md4
    [20] =&gt; md5
    [21] =&gt; md_gost94
    [22] =&gt; ripemd160
    [23] =&gt; sha
    [24] =&gt; sha1
    [25] =&gt; sha224
    [26] =&gt; sha256
    [27] =&gt; sha384
    [28] =&gt; sha512
    [29] =&gt; streebog256
    [30] =&gt; streebog512
    [31] =&gt; whirlpool
)
Array
(
    [2] =&gt; DSA-SHA1
    [3] =&gt; DSA-SHA1-old
    [4] =&gt; DSS1
    [12] =&gt; RSA-MD4
    [13] =&gt; RSA-MD5
    [14] =&gt; RSA-RIPEMD160
    [15] =&gt; RSA-SHA
    [16] =&gt; RSA-SHA1
    [17] =&gt; RSA-SHA1-2
    [18] =&gt; RSA-SHA224
    [19] =&gt; RSA-SHA256
    [20] =&gt; RSA-SHA384
    [21] =&gt; RSA-SHA512
    [30] =&gt; dsaWithSHA1
    [31] =&gt; dss1
    [35] =&gt; md4WithRSAEncryption
    [37] =&gt; md5WithRSAEncryption
    [39] =&gt; ripemd
    [41] =&gt; ripemd160WithRSA
    [42] =&gt; rmd160
    [45] =&gt; sha1WithRSAEncryption
    [47] =&gt; sha224WithRSAEncryption
    [49] =&gt; sha256WithRSAEncryption
    [51] =&gt; sha384WithRSAEncryption
    [53] =&gt; sha512WithRSAEncryption
    [54] =&gt; shaWithRSAEncryption
    [55] =&gt; ssl2-md5
    [56] =&gt; ssl3-md5
    [57] =&gt; ssl3-sha1
)
</code></pre>
<p>In <code>openssl</code> You can get a list of available cipher methods by calling</p>
<p></p>
<pre><code class="language-console">$ openssl list-message-digest-commands
</code></pre>
<p>The above example will output something similar to:</p>
<p></p>
<pre><code class="language-console">md2
md4
md5
mdc2
rmd160
sha
sha1
</code></pre>
<p></p>

<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="addcomments.jsp"%>
      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 
         
         
         <%@ include file="related-go.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         
         <%@ include file="related-window-crypto.jsp"%>

		 
          <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         <%@ include file="related-linux.jsp"%>
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>


      </div>
      
      <!-- /.row -->

    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>