<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="php openssl tutorial on openssl_get_cipher_methods, php openssl_get_cipher_methods example ">
    <meta name="keywords" content="openssl list-cipher-commands openssl_get_cipher_methods, php openssl_get_cipher_methods example, php cryptography topics, php security, php interview questions">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>php openssl tutorial on openssl_get_cipher_methods</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/php-ciphermethod.jsp"
  },
  "name" : "go lang encoding decoding",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "php openssl tutorial on openssl_get_cipher_method",
  "image":"https://8gwifi.org/docs/img/php/php-ciphermethod.png",
  "datePublished" : "2018-12-12",
  "dateModified": "2018-12-12",
  "articleSection" : "php openssl tutorial on openssl_get_cipher_method",
  "articleBody" : [ "php openssl example ", "php openssl_get_cipher_method "],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">php openssl_get_cipher_methods example</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Wednesday December 12 , 2018</p>
          </p>
          
          
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          
          <hr>
<p>In <code>openssl</code> You can get a list of available cipher methods by calling</p>
<pre><code class="language-console">$ openssl list-cipher-commands
</code></pre>
<p>The above example will output something similar to:</p>
<pre><code class="language-console">aes-128-cbc
aes-128-ecb
aes-192-cbc
aes-192-ecb
aes-256-cbc
aes-256-ecb
base64
bf
bf-cbc
bf-cfb
bf-ecb
bf-ofb
cast
cast-cbc
cast5-cbc
cast5-cfb
cast5-ecb
cast5-ofb
des
des-cbc
des-cfb
des-ecb
des-ede
des-ede-cbc
des-ede-cfb
des-ede-ofb
des-ede3
des-ede3-cbc
des-ede3-cfb
des-ede3-ofb
des-ofb
des3
desx
rc2
rc2-40-cbc
rc2-64-cbc
rc2-cbc
rc2-cfb
rc2-ecb
rc2-ofb
rc4
rc4-40
seed
seed-cbc
seed-cfb
seed-ecb
seed-ofb
</code></pre>
<h2><a id="openssl_get_cipher_methods_58"></a>openssl_get_cipher_methods</h2>
<p>openssl_get_cipher_methods  Gets available cipher methods. Supported PHP Versions (<strong>PHP 5 &gt;= 5.3.0, PHP 7</strong>)</p>
<p><strong>Examples</strong></p>
<p><strong><strong>openssl_get_cipher_methods()</strong>  example</strong>  Shows how the available ciphers might look, and also which aliases might be available.</p>
<pre><code class="language-php"><span class="hljs-comment">/**  
 * Created by https://8gwifi.org  
 * User: Anish Nath  
 * Date: 2018-12-10  
 * Time: 15:13  
 */</span>  
  
<span class="hljs-preprocessor">&lt;?php</span>  
<span class="hljs-variable">$ciphers</span> = openssl_get_cipher_methods();  
<span class="hljs-variable">$ciphers_and_aliases</span> = openssl_get_cipher_methods(<span class="hljs-keyword">true</span>);  
<span class="hljs-variable">$cipher_aliases</span> = array_diff(<span class="hljs-variable">$ciphers_and_aliases</span>, <span class="hljs-variable">$ciphers</span>);  
print_r(<span class="hljs-variable">$ciphers</span>);  
print_r(<span class="hljs-variable">$cipher_aliases</span>);  
<span class="hljs-preprocessor">?&gt;</span>
</code></pre>
<p>The above example will output something similar to:</p>
<pre><code class="language-console">$ /usr/bin/php get_cipher_methods.php
/**
 * Created by https://8gwifi.org
 * User: Anish Nath
 * Date: 2018-12-10
 * Time: 15:13
 */
Array
(
    [0] =&gt; AES-128-CBC
    [1] =&gt; AES-128-CFB
    [2] =&gt; AES-128-CFB1
    [3] =&gt; AES-128-CFB8
    [4] =&gt; AES-128-CTR
    [5] =&gt; AES-128-ECB
    [6] =&gt; AES-128-OFB
    [7] =&gt; AES-128-XTS
    [8] =&gt; AES-192-CBC
    [9] =&gt; AES-192-CFB
    [10] =&gt; AES-192-CFB1
    [11] =&gt; AES-192-CFB8
    [12] =&gt; AES-192-CTR
    [13] =&gt; AES-192-ECB
    [14] =&gt; AES-192-OFB
    [15] =&gt; AES-256-CBC
    [16] =&gt; AES-256-CFB
    [17] =&gt; AES-256-CFB1
    [18] =&gt; AES-256-CFB8
    [19] =&gt; AES-256-CTR
    [20] =&gt; AES-256-ECB
    [21] =&gt; AES-256-OFB
    [22] =&gt; AES-256-XTS
    [23] =&gt; BF-CBC
    [24] =&gt; BF-CFB
    [25] =&gt; BF-ECB
    [26] =&gt; BF-OFB
    [27] =&gt; CAMELLIA-128-CBC
    [28] =&gt; CAMELLIA-128-CFB
    [29] =&gt; CAMELLIA-128-CFB1
    [30] =&gt; CAMELLIA-128-CFB8
    [31] =&gt; CAMELLIA-128-ECB
    [32] =&gt; CAMELLIA-128-OFB
    [33] =&gt; CAMELLIA-192-CBC
    [34] =&gt; CAMELLIA-192-CFB
    [35] =&gt; CAMELLIA-192-CFB1
    [36] =&gt; CAMELLIA-192-CFB8
    [37] =&gt; CAMELLIA-192-ECB
    [38] =&gt; CAMELLIA-192-OFB
    [39] =&gt; CAMELLIA-256-CBC
    [40] =&gt; CAMELLIA-256-CFB
    [41] =&gt; CAMELLIA-256-CFB1
    [42] =&gt; CAMELLIA-256-CFB8
    [43] =&gt; CAMELLIA-256-ECB
    [44] =&gt; CAMELLIA-256-OFB
    [45] =&gt; CAST5-CBC
    [46] =&gt; CAST5-CFB
    [47] =&gt; CAST5-ECB
    [48] =&gt; CAST5-OFB
    [49] =&gt; ChaCha
    [50] =&gt; DES-CBC
    [51] =&gt; DES-CFB
    [52] =&gt; DES-CFB1
    [53] =&gt; DES-CFB8
    [54] =&gt; DES-ECB
    [55] =&gt; DES-EDE
    [56] =&gt; DES-EDE-CBC
    [57] =&gt; DES-EDE-CFB
    [58] =&gt; DES-EDE-OFB
    [59] =&gt; DES-EDE3
    [60] =&gt; DES-EDE3-CBC
    [61] =&gt; DES-EDE3-CFB
    [62] =&gt; DES-EDE3-CFB1
    [63] =&gt; DES-EDE3-CFB8
    [64] =&gt; DES-EDE3-OFB
    [65] =&gt; DES-OFB
    [66] =&gt; DESX-CBC
    [67] =&gt; GOST 28147-89
    [68] =&gt; RC2-40-CBC
    [69] =&gt; RC2-64-CBC
    [70] =&gt; RC2-CBC
    [71] =&gt; RC2-CFB
    [72] =&gt; RC2-ECB
    [73] =&gt; RC2-OFB
    [74] =&gt; RC4
    [75] =&gt; RC4-40
    [76] =&gt; RC4-HMAC-MD5
    [77] =&gt; aes-128-cbc
    [78] =&gt; aes-128-cfb
    [79] =&gt; aes-128-cfb1
    [80] =&gt; aes-128-cfb8
    [81] =&gt; aes-128-ctr
    [82] =&gt; aes-128-ecb
    [83] =&gt; aes-128-gcm
    [84] =&gt; aes-128-ofb
    [85] =&gt; aes-128-xts
    [86] =&gt; aes-192-cbc
    [87] =&gt; aes-192-cfb
    [88] =&gt; aes-192-cfb1
    [89] =&gt; aes-192-cfb8
    [90] =&gt; aes-192-ctr
    [91] =&gt; aes-192-ecb
    [92] =&gt; aes-192-gcm
    [93] =&gt; aes-192-ofb
    [94] =&gt; aes-256-cbc
    [95] =&gt; aes-256-cfb
    [96] =&gt; aes-256-cfb1
    [97] =&gt; aes-256-cfb8
    [98] =&gt; aes-256-ctr
    [99] =&gt; aes-256-ecb
    [100] =&gt; aes-256-gcm
    [101] =&gt; aes-256-ofb
    [102] =&gt; aes-256-xts
    [103] =&gt; bf-cbc
    [104] =&gt; bf-cfb
    [105] =&gt; bf-ecb
    [106] =&gt; bf-ofb
    [107] =&gt; camellia-128-cbc
    [108] =&gt; camellia-128-cfb
    [109] =&gt; camellia-128-cfb1
    [110] =&gt; camellia-128-cfb8
    [111] =&gt; camellia-128-ecb
    [112] =&gt; camellia-128-ofb
    [113] =&gt; camellia-192-cbc
    [114] =&gt; camellia-192-cfb
    [115] =&gt; camellia-192-cfb1
    [116] =&gt; camellia-192-cfb8
    [117] =&gt; camellia-192-ecb
    [118] =&gt; camellia-192-ofb
    [119] =&gt; camellia-256-cbc
    [120] =&gt; camellia-256-cfb
    [121] =&gt; camellia-256-cfb1
    [122] =&gt; camellia-256-cfb8
    [123] =&gt; camellia-256-ecb
    [124] =&gt; camellia-256-ofb
    [125] =&gt; cast5-cbc
    [126] =&gt; cast5-cfb
    [127] =&gt; cast5-ecb
    [128] =&gt; cast5-ofb
    [129] =&gt; chacha
    [130] =&gt; des-cbc
    [131] =&gt; des-cfb
    [132] =&gt; des-cfb1
    [133] =&gt; des-cfb8
    [134] =&gt; des-ecb
    [135] =&gt; des-ede
    [136] =&gt; des-ede-cbc
    [137] =&gt; des-ede-cfb
    [138] =&gt; des-ede-ofb
    [139] =&gt; des-ede3
    [140] =&gt; des-ede3-cbc
    [141] =&gt; des-ede3-cfb
    [142] =&gt; des-ede3-cfb1
    [143] =&gt; des-ede3-cfb8
    [144] =&gt; des-ede3-ofb
    [145] =&gt; des-ofb
    [146] =&gt; desx-cbc
    [147] =&gt; gost89
    [148] =&gt; gost89-cnt
    [149] =&gt; gost89-ecb
    [150] =&gt; id-aes128-GCM
    [151] =&gt; id-aes192-GCM
    [152] =&gt; id-aes256-GCM
    [153] =&gt; rc2-40-cbc
    [154] =&gt; rc2-64-cbc
    [155] =&gt; rc2-cbc
    [156] =&gt; rc2-cfb
    [157] =&gt; rc2-ecb
    [158] =&gt; rc2-ofb
    [159] =&gt; rc4
    [160] =&gt; rc4-40
    [161] =&gt; rc4-hmac-md5
)
Array
(
    [23] =&gt; AES128
    [24] =&gt; AES192
    [25] =&gt; AES256
    [26] =&gt; BF
    [49] =&gt; CAMELLIA128
    [50] =&gt; CAMELLIA192
    [51] =&gt; CAMELLIA256
    [52] =&gt; CAST
    [53] =&gt; CAST-cbc
    [59] =&gt; DES
    [76] =&gt; DES3
    [77] =&gt; DESX
    [80] =&gt; RC2
    [116] =&gt; aes128
    [117] =&gt; aes192
    [118] =&gt; aes256
    [119] =&gt; bf
    [124] =&gt; blowfish
    [143] =&gt; camellia128
    [144] =&gt; camellia192
    [145] =&gt; camellia256
    [146] =&gt; cast
    [147] =&gt; cast-cbc
    [153] =&gt; des
    [170] =&gt; des3
    [171] =&gt; desx
    [179] =&gt; rc2
)
Process finished with exit code 0
</code></pre>

<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="addcomments.jsp"%>
      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 
         
         
         <%@ include file="related-go.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         
         <%@ include file="related-window-crypto.jsp"%>

		 
          <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         
         <%@ include file="related-openstack.jsp"%>
         <%@ include file="related-linux.jsp"%>
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>


      </div>
      
      <!-- /.row -->

    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>