<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="how to access prometheus operator dashbaord, alert manager, grafana ">
    <meta name="keywords" content="promethues dashbaord access, alert manager, grafana login ">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>Prometheus operator dashbaord access, alert manager and grafana</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/prometheus-dashboard.jsp"
  },
  "name" : "Prometheus operator dashbaord access, alert manager and grafana",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Prometheus operator dashbaord access, alert manager and grafana",
  "image":"https://8gwifi.org/docs/img/prometheus/promethoudoperator.png",
  "datePublished" : "2019-01-09",
  "dateModified": "2018-01-09",
  "articleSection" : "Prometheus Dashboards Access",
  "articleBody" : [ "Prometheus ports","Prometheus-Operator UI","Prometheus Alert-Manager UI","Prometheus Grafana UI","prometheus"]
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4" class="mt-4">Prometheus Dashboards Access</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Wednesday January 9, 2019</p>
          </p>
          
          <img class="img-fluid rounded" src="img/prometheus/promethoudoperator.png" height="400" width="500" alt="Referefce ">
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>
          
<p>The default installation of prometheus comes with these three dashboards</p>
<ul>
<li>Prometheus-Operator UI</li>
<li>AlertManager UI</li>
<li>Grafana UI</li>
</ul>
<p>Before Accessing the UI make sure you have all the prometheus necessary pods are up and running</p>
<pre><code class="language-console">root@kube-master:# kubectl --namespace monitoring get pods 
NAME                                                     READY     STATUS    RESTARTS   AGE
alertmanager-prometheus-operator-alertmanager-0          2/2       Running   0          53m
prometheus-operator-grafana-7654f69d89-mxwwh             3/3       Running   0          53m
prometheus-operator-kube-state-metrics-cdf84dd85-fkdvs   1/1       Running   0          53m
prometheus-operator-operator-54f7767b66-rdh8c            1/1       Running   0          53m
prometheus-operator-prometheus-node-exporter-6ldmm       1/1       Running   0          53m
prometheus-operator-prometheus-node-exporter-9gtqt       1/1       Running   0          53m
prometheus-prometheus-operator-prometheus-0              3/3       Running   1          53m
</code></pre>
<h2><a id="Prometheus_ports_22"></a>Prometheus ports</h2>
<p>These are the standard ports which will be helpful while dealing with Prometheus server and it’s associated service.</p>
<ul>
<li>9090 - Prometheus server</li>
<li>9091 - Pushgateway</li>
<li>9092 - UNALLOCATED (to avoid collision with Kafka)</li>
<li>9093 - Alertmanager</li>
<li>9094 - Alertmanager clustering</li>
</ul>
<p>To view the TargetPort  under the prometheus namespace <strong>monitoring</strong></p>
<pre><code class="language-console">root@kube-master:/home/ansible# kubectl describe svc -n  monitoring
Name:              alertmanager-operated
Namespace:         monitoring
Labels:            operated-alertmanager=true
Annotations:       &lt;none&gt;
Selector:          app=alertmanager
Type:              ClusterIP
IP:                None
Port:              web  9093/TCP
TargetPort:        9093/TCP
Endpoints:         10.244.1.102:9093
Port:              mesh  6783/TCP
TargetPort:        6783/TCP
Endpoints:         10.244.1.102:6783
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operated
Namespace:         monitoring
Labels:            operated-prometheus=true
Annotations:       &lt;none&gt;
Selector:          app=prometheus
Type:              ClusterIP
IP:                None
Port:              web  9090/TCP
TargetPort:        web/TCP
Endpoints:         10.244.1.103:9090
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operator-alertmanager
Namespace:         monitoring
Labels:            app=prometheus-operator-alertmanager
                   chart=prometheus-operator-1.5.2
                   heritage=Tiller
                   release=prometheus-operator
Annotations:       &lt;none&gt;
Selector:          alertmanager=prometheus-operator-alertmanager,app=alertmanager
Type:              ClusterIP
IP:                10.105.171.62
Port:              web  9093/TCP
TargetPort:        9093/TCP
Endpoints:         10.244.1.102:9093
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operator-grafana
Namespace:         monitoring
Labels:            app=grafana
                   chart=grafana-1.19.1
                   heritage=Tiller
                   release=prometheus-operator
Annotations:       &lt;none&gt;
Selector:          app=grafana,release=prometheus-operator
Type:              ClusterIP
IP:                10.111.200.84
Port:              service  80/TCP
TargetPort:        3000/TCP
Endpoints:         10.244.1.99:3000
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operator-kube-state-metrics
Namespace:         monitoring
Labels:            app=kube-state-metrics
                   chart=kube-state-metrics-0.12.1
                   heritage=Tiller
                   release=prometheus-operator
Annotations:       prometheus.io/scrape=true
Selector:          app=kube-state-metrics,release=prometheus-operator
Type:              ClusterIP
IP:                10.97.64.74
Port:              http  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.244.1.100:8080
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operator-operator
Namespace:         monitoring
Labels:            app=prometheus-operator-operator
                   chart=prometheus-operator-1.5.2
                   heritage=Tiller
                   release=prometheus-operator
Annotations:       &lt;none&gt;
Selector:          app=prometheus-operator-operator,release=prometheus-operator
Type:              ClusterIP
IP:                10.105.149.5
Port:              http  8080/TCP
TargetPort:        http/TCP
Endpoints:         10.244.1.101:8080
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operator-prometheus
Namespace:         monitoring
Labels:            app=prometheus-operator-prometheus
                   chart=prometheus-operator-1.5.2
                   heritage=Tiller
                   release=prometheus-operator
Annotations:       &lt;none&gt;
Selector:          app=prometheus,prometheus=prometheus-operator-prometheus
Type:              ClusterIP
IP:                10.105.66.183
Port:              web  9090/TCP
TargetPort:        web/TCP
Endpoints:         10.244.1.103:9090
Session Affinity:  None
Events:            &lt;none&gt;


Name:              prometheus-operator-prometheus-node-exporter
Namespace:         monitoring
Labels:            app=prometheus-node-exporter
                   chart=prometheus-node-exporter-1.1.0
                   heritage=Tiller
                   jobLabel=node-exporter
                   release=prometheus-operator
Annotations:       prometheus.io/scrape=true
Selector:          app=prometheus-node-exporter,release=prometheus-operator
Type:              ClusterIP
IP:                10.108.197.197
Port:              metrics  9100/TCP
TargetPort:        9100/TCP
Endpoints:         172.16.2.13:9100,172.16.2.7:9100
Session Affinity:  None
Events:            &lt;none&gt;
</code></pre>
<h2><a id="PrometheusOperator_UI_170"></a>Prometheus-Operator UI</h2>
<pre><code class="language-console">kubectl port-forward -n monitoring prometheus-prometheus-operator-prometheus-0  9090
</code></pre>
<p>Open web browser to <a href="http://localhost:9090/">http://localhost:9090</a> , you will access the Prometheus interface.</p>
<p><img class="img-fluid rounded" src="img/prometheus/targets.png" alt=""></p>
<h2><a id="Prometheus_AlertManager_UI_179"></a>Prometheus Alert-Manager UI</h2>
<pre><code class="language-console">kubectl port-forward -n monitoring alertmanager-prometheus-operator-alertmanager-0    9090:9093
</code></pre>
<p>Open web browser to <a href="http://localhost:9093/">http://localhost:9093</a> , you will access the Prometheus interface.</p>
<p><img class="img-fluid rounded" src="img/prometheus/alertmanager.png" alt=""></p>
<h2><a id="Prometheus_Grafana_UI_189"></a>Prometheus Grafana UI</h2>
<pre><code class="language-console">kubectl port-forward -n monitoring prometheus-operator-grafana-7654f69d89-mxwwh 3000:3000
</code></pre>
<p><strong>UI Credentials are </strong>admin:admin or admin:promo-operator</p>
<p><img class="img-fluid rounded" src="img/prometheus/garfana.png" alt=""></p>
<h3><a id="Further_Reading_62"></a>Further Reading</h3>
<ol>
<li>Checkout how to deploy <a href="kube-nginx.jsp">HTTPS Secure Nginx deploymet in kubernetes</a></li>
</ol>


<%@ include file="thanks.jsp"%>


<hr>


      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          
          <%@ include file="related-kube.jsp"%>
          
          <!-- Article Widget -->
         <%@ include file="related-linux.jsp"%>
         
           <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         
         
         
         <%@ include file="related-cryptography.jsp"%>
          <%@ include file="related-window-crypto.jsp"%>
          
          <%@ include file="related-openstack.jsp"%>
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>

      </div>
      <!-- /.row -->


	<%@ include file="addcomments.jsp"%>
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>