<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="How To Configure MFA on Centos and Ubuntu with Google Authenticator">
    <meta name="keywords" content="How To Configure MFA on Centos and Ubuntu with Google Authenticator, centos7 mfa config with google authenticator, ubuntu mfa config with google authenticator, ssh Server hardening">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>How To Configure MFA on Centos and Ubuntu with Google Authenticator</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/ssh1.jsp"
  },
  "name" : "wenty Steps to obtain SSH Hardening",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Twenty Steps to obtain SSH Hardening",
  "image":"https://8gwifi.org/docs/img/ssh6.png",
  "datePublished" : "2019-10-18",
  "dateModified": "2019-10-18",
  "articleSection" : "How To Configure MFA on Centos and Ubuntu with Google Authenticator",
  "articleBody" : [ "TOTP","Allow/Deny rules", "Single factor authentication", "Google Authenticator", "Install dependencies", "Install google-authenticator", "Edit /etc/pam.d/sshd", "Activate the two-factor authentication for a user", "Disable root SSH access" , "Generate TOTP codes" , "demo" ],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :   {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


  </head>

  <body>

    <!-- Navigation -->
   <%@ include file="navigation.jsp"%> 

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">How To Configure MFA on Centos and Ubuntu with Google Authenticator</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on Friday October 18/2019</p>

          <hr>

        
 
          <img class="img-fluid rounded" src="img/ssh6.png" alt="Referefce 8gwifi.org">

           <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>

          <hr>

          <!-- Post Content -->
        <p class="has-line-data" data-line-start="4" data-line-end="5"><strong>Before We Begin:-</strong></p>
<p class="has-line-data" data-line-start="6" data-line-end="7">Authentication factor can be of following types: (CISSP Stuff)</p>
<ul>
<li class="has-line-data" data-line-start="8" data-line-end="9"><strong>Something you know</strong>: A secret or password or PIN</li>
<li class="has-line-data" data-line-start="9" data-line-end="10"><strong>Something you have</strong>: Smart card / token / Mobile Phone</li>
<li class="has-line-data" data-line-start="10" data-line-end="12"><strong>Something you are</strong>: Facial Recognition, Biometrics</li>
</ul>
<p class="has-line-data" data-line-start="12" data-line-end="13"><strong>Single factor authentication</strong> uses one of the types mentioned above as their authentication mechanism for example use of a password to connect to your Linux server</p>
<p class="has-line-data" data-line-start="14" data-line-end="15">A good example of two-factor authentication is the performing online Transaction, in this case</p>
<ul>
<li class="has-line-data" data-line-start="16" data-line-end="17"><strong>Something you know</strong> : The Bank user credentials</li>
<li class="has-line-data" data-line-start="17" data-line-end="19"><strong>Something You have</strong> : Phone Number linked with account used to sent <strong>OTP</strong>  for the Two step verification</li>
</ul>
<p class="has-line-data" data-line-start="19" data-line-end="20">In this tutorial we will configure our friend SSH to go with MFA, but before that let's take a small chit-chat on <strong>TOTP: Time-Based One-Time Password Algorithm</strong></p>
<p class="has-line-data" data-line-start="21" data-line-end="22"><strong>TOTP</strong>  : The Time-based One-Time Password algorithm (TOTP) is an extension of the HMAC-based One-time Password algorithm (HOTP) generating a one-time password by instead taking uniqueness from the current time.</p>
<p class="has-line-data" data-line-start="23" data-line-end="24"><strong>Google Authenticator</strong> is a software-based authenticator that implements two-step verification services using the Time-based One-time Password Algorithm and to achive 2FA in Centos and Ubuntu we will be using <a href="https://github.com/google/google-authenticator-libpam">google-authenticator-libpam</a> PAM Module.</p>
<p class="has-line-data" data-line-start="25" data-line-end="26">Let's begin the configuring Google Authenticator PAM Module</p>
<ul>
<li class="has-line-data" data-line-start="27" data-line-end="28">Tested on Ubuntu 16.04/18.04</li>
<li class="has-line-data" data-line-start="28" data-line-end="30">Centos7</li>
</ul>
<h3 class="code-line" data-line-start=30 data-line-end=31 ><a id="1_Install_googleauthenticator_30"></a>1. Install google-authenticator</h3>
<ul>
<li class="has-line-data" data-line-start="32" data-line-end="33">Ubuntu</li>
</ul>
<pre><code class="html">sudo apt-get install libpam-google-authenticator
</code></pre>
<ul>
<li class="has-line-data" data-line-start="37" data-line-end="38">Centos</li>
</ul>
<pre><code class="html">yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum install google-authenticator
</code></pre>
<h3 class="code-line" data-line-start=43 data-line-end=44 ><a id="2_Edit_the_configuration_files_43"></a>2. Edit the configuration files</h3>
<ul>
<li class="has-line-data" data-line-start="45" data-line-end="51">
<p class="has-line-data" data-line-start="45" data-line-end="46">Edit  <code>/etc/pam.d/sshd</code>  and add this directive add it in the beginning of the file. In this way the system will ask first authentication code and only then will ask password.</p>
<pre><code class="html"># Google Authenticator
auth required pam_google_authenticator.so
</code></pre>
</li>
</ul>
<ul>
<li class="has-line-data" data-line-start="53" data-line-end="60">
<p class="has-line-data" data-line-start="53" data-line-end="54">Edit  <code>/etc/ssh/sshd_config</code>  and modify or add these directives:</p>
<pre><code class="html">ChallengeResponseAuthentication yes
UsePAM yes
PasswordAuthentication no
</code></pre>
</li>
</ul>
<h3 class="code-line" data-line-start=62 data-line-end=63 ><a id="3_Activate_the_twofactor_authentication_for_a_user_62"></a>3. Activate the two-factor authentication for a user</h3>
<p class="has-line-data" data-line-start="64" data-line-end="65">Switch to the user who should use the two-factor authentication and type in the terminal:</p>
<pre><code class="html">[anish@1242d27bd57c ~]$ google-authenticator
</code></pre>
<p class="has-line-data" data-line-start="69" data-line-end="70"><img class="img-fluid rounded" src="img/ssh3.png" alt="Google Authenticator Configuration"></p>
<pre><code class="html">O4IRDBDELSPSEWFXF2USVKIXIY
Your verification code is <strong>560634</strong><br>
Your emergency scratch codes are:<br>
33932408
43900036
59855459
94779765
560436451
</code></pre>
<p class="has-line-data" data-line-start="81" data-line-end="82">you can also find these details in the user home location</p>
<pre><code class="html">anish@1242d27bd57c ~$ cat .google_authenticator
O4IRDBDELSPSEWFXF2USVKIXIY
RATE_LIMIT 3 30
WINDOW_SIZE 17
DISALLOW_REUSE
TOTP_AUTH
33932408
43900036
59855459
94779765
56043645
</code></pre>
<p class="has-line-data" data-line-start="98" data-line-end="99"><img class="img-fluid rounded" src="img/ssh4.png" alt="Google Authenticator Configuration"></p>
<h3 class="code-line" data-line-start=100 data-line-end=101 ><a id="4_Generate_TOTP_codes_100"></a>4. Generate TOTP codes</h3>
<p class="has-line-data" data-line-start="102" data-line-end="103">The Secret Key <strong>O4IRDBDELSPSEWFXF2USVKIXIY</strong> is used to generate the Authentication code</p>
<p class="has-line-data" data-line-start="104" data-line-end="105">We will use the Google Authenticator app available for Android (in the <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2">Play Store</a>) and iOS (in <a href="https://itunes.apple.com/us/app/google-authenticator/id388497605">iTunes</a>) to generate authentication codes.</p>
<p class="has-line-data" data-line-start="106" data-line-end="107"><img  class="img-fluid rounded" src="img/ssh5.png" alt="Google Authenticator Code Generated from the APP "></p>

<h3 class="code-line" data-line-start=108 data-line-end=109 ><a id="5_Demo_108"></a>5. Testing</h3>

<pre><code class="html">
[root@1242d27bd57c /]# ssh anish@172.17.0.4
Verification code: 
Password: 
Last login: Fri Oct 18 08:34:22 2019 from 1242d27bd57c
</code></pre>

<h3 class="code-line" data-line-start=108 data-line-end=109 ><a id="5_Demo_108"></a>6. Demo</h3>

<p><h2>Centos Video Demo </h2> </p>
<iframe width="420" height="315"
src="https://youtube.com/embed/TCYdk1t3Mzw">
</iframe>

<p><h2>Ubuntu Video Demo </h2> </p>
<iframe width="420" height="315"
src="https://youtube.com/embed/lzsmSvruWLo">
</iframe>

<hr>

<p><a href="ssh.jsp">Next Reading Twenty Step to Harden SSH </a></p>

<hr>
<%@ include file="thanks.jsp"%>
          <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
          

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 

          <!-- Article Widget -->
         <%@ include file="related-linux.jsp"%>
         
           <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         <%@ include file="related-openstack.jsp"%>
         
         <%@ include file="related-cryptography.jsp"%>
         <%@ include file="related-window-crypto.jsp"%>
         
         
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
        </div>

      </div>
      <!-- /.row -->
      <%@ include file="addcomments.jsp"%>

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>