<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt ">
    <meta name="keywords" content="Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt, web crypto api aes encryption decryption example aes-ctr,aes-gcm,aes-cbc,aes-ctr , windo.crypto javascript examples, Web Cryptography API">
    <meta name="author" content="Anish nath">
    <meta name="robots" content="index,follow" />
	<meta name="googlebot" content="index,follow" />
	<meta name="resource-type" content="document" />
	<meta name="classification" content="tools" />
	<meta name="language" content="en" />

    <title>Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt </title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/blog-post.css" rel="stylesheet">
    
    <link rel="stylesheet"  href="css/highlight/default.min.css">
	<script src="css/highlight/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	
	
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://8gwifi.org/docs/window-crypto-aes2.jsp"
  },
  "name" : "Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt",
  "author" : {
    "@type" : "Person",
    "name" : "Anish"
  },
  "headline": "Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt ",
  "image":"https://8gwifi.org/docs/img/window-crypto-aes2.png",
  "datePublished" : "2018-09-17",
  "dateModified": "2018-08-17",
  "articleSection" : "web crypto api aes encryption decryption example aes-ctr,aes-gcm,aes-cbc,aes-ctr ",
  "articleBody" : [ "Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt ", "SubtleCrypto.generateKey()" , "The webcrypto api java script example AES-GCM generateKey Encryption and Decryption"],
  "publisher" : {
    "@type" : "Organization",
    "name" : "8gwifi.org Tech Blog",
    "logo" :  {
      "@type": "ImageObject",
      "url": "https://8gwifi.org/docs/img/logo.jpg"
    }
  }
}
</script>


    <script type="text/javascript">
    var iv = crypto.getRandomValues(new Uint8Array(16));
    var secretKey;

    window.crypto.subtle.generateKey({
                name: "AES-GCM",
                length: 256, //can be  128, 192, or 256
            },
            false, //whether the key is extractable (i.e. can be used in exportKey)
            ["encrypt", "decrypt"] //can "encrypt", "decrypt" or  "wrapKey", or "unwrapKey"
        ).then(function(key) {
            secretKey = key;
        })
        .catch(function(err) {
            console.error(err);
        });


    function AES256_GCM_ENCRYPT() {

        if (secretKey == null) {
            alert("Failed to Generate AES Keys Check The browser Comptabilty ")
            return;
        }

        var plainText = document.getElementById("plainTextGCM").value;

        return crypto.subtle.encrypt({
            name: "aes-gcm",
            iv: iv,
            tagLength: 128 //can be 32, 64, 96, 104, 112, 120 or 128 (default)
        }, secretKey, asciiToUint8Array(plainText)).then(function(cipherText) {
            document.getElementById("cipherTextGCM").value = bytesToHexString(cipherText);
        }, failAndLog);

    }

    function AES256_GCM_decrypt() {

        if (secretKey == null) {
            alert("Failed to Generate AES Keys Check The browser Comptabilty ")
            return;
        }

        var cipherText = document.getElementById("cipherTextGCM").value;
        crypto.subtle.decrypt({
                name: "aes-gcm",
                iv: iv,
                tagLength: 128 //can be 32, 64, 96, 104, 112, 120 or 128 (default)
            },
            secretKey,
            hexStringToUint8Array(cipherText)
        ).then(
            function(plainText) {
                document.getElementById("resultGCM").innerHTML = "Result: " + bytesToASCIIString(plainText);
            },
            function(result) {
                document.getElementById("resultGCM").innerHTML = "Result: " + result;
            });
    }

    function bytesToHexString(bytes) {
        if (!bytes)
            return null;

        bytes = new Uint8Array(bytes);
        var hexBytes = [];

        for (var i = 0; i < bytes.length; ++i) {
            var byteString = bytes[i].toString(16);
            if (byteString.length < 2)
                byteString = "0" + byteString;
            hexBytes.push(byteString);
        }

        return hexBytes.join("");
    }


    function bytesToASCIIString(bytes) {
        return String.fromCharCode.apply(null, new Uint8Array(bytes));
    }

    function hexStringToUint8Array(hexString) {
        if (hexString.length % 2 != 0)
            throw "Invalid hexString";
        var arrayBuffer = new Uint8Array(hexString.length / 2);

        for (var i = 0; i < hexString.length; i += 2) {
            var byteValue = parseInt(hexString.substr(i, 2), 16);
            if (byteValue == NaN)
                throw "Invalid hexString";
            arrayBuffer[i / 2] = byteValue;
        }

        return arrayBuffer;
    }

    function failAndLog(error) {
        console.log(error);
    }

    function asciiToUint8Array(str) {
        var chars = [];
        for (var i = 0; i < str.length; ++i)
            chars.push(str.charCodeAt(i));
        return new Uint8Array(chars);
    }

</script>

  </head>

  <body>

    <!-- Navigation -->
 	<%@ include file="navigation.jsp"%>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Web Crypto API AES-GCM - generateKey/Encrypt/Decrypt</h1>

          <!-- Author -->
          <p class="lead">
            by
            <a href="https://www.linkedin.com/in/anishnath">Anish</a>
            <p>Posted on Monday september 17, 2018</p>
          </p>
          
          
          
          <%@ include file="footer_adsense.jsp"%>
           <%@ include file="analytics.jsp"%>
           
          <hr>

<p><mark>This sample chapter </mark> extracted from the book, <a href="https://leanpub.com/crypto">Cryptography for JavaScript Developers</a>. </p>
<p><iframe width='160' height='400' src='https://leanpub.com/cryptojs/embed' frameborder='0' allowtransparency='true'></iframe></p>
<hr>

<p>The <a href="https://www.w3.org/TR/WebCryptoAPI/#dfn-Crypto">Crypto</a> interface represents an interface to general purpose cryptographic functionality including a cryptographically strong pseudo-random number generator seeded with truly random values.</p>
<p>The <strong>SubtleCrypto.generateKey()</strong> method returns a Promise of a newly generated CryptoKey</p>
<p>The Syntax</p>
<pre><code class="html">var result = crypto.subtle.generateKey(algo, extractable, keyUsages);
</code></pre>
<ul>
<li>
<p><strong>algo</strong>: Supported algo are: AES-CBC, AES-CTR, AES-GCM, RSA-OAEP, AES-KW, HMAC, RSASSA-PKCS1-v1_5, ECDSA, ECDH, and DH.</p>
</li>
<li>
<p><strong>extractable</strong> is a Boolean indicating if the key can be extracted from the CryptoKey object at a later stage</p>
</li>
<li>
<p><strong>keyUsages</strong>  is an Array indicating what can be done with the newly generated key. Possible values of the array are for AES encryption:</p>
<ul>
<li><strong>encrypt</strong>, allowing the key to be used for encrypting messages.</li>
<li><strong>decrypt</strong>, allowing the key to be used for decrypting messages.</li>
<li><strong>wrapKey</strong>, allowing the key to wrap a symmetric key for usage (transfer, storage) in unsecure environments.</li>
<li><strong>unwrapKey</strong>, allowing the key to unwrap a symmetric key for usage (transfer, storage) in unsecure environments.</li>
</ul>
</li>
</ul>
<hr>
<h3 class="mt-4"><a id="The_Demo_19"></a>The Demo</h3>
<p>
<div>
        Plain Text: <input class="form-control" type="text" id="plainTextGCM" value="Hello 8gwifi.org">
        <button type="button" class="btn btn-primary" onclick="AES256_GCM_ENCRYPT()">AES256-GCM-ENCRYPT</button>
    </div>
    <div>
        Cipher Text: <input class="form-control" type="text" id="cipherTextGCM" size="50">
        <button type="button" class="btn btn-primary" onclick="AES256_GCM_decrypt()">AES256_GCM_decrypt</button>
    </div>
    <div id="resultGCM">
        Result:
    </div>
</p>
<hr>
<p><strong>The webcrypto api  java script example AES-GCM  generateKey Encryption and Decryption</strong></p>
<pre><code class="html"> var iv = crypto.getRandomValues(new Uint8Array(16));
 var secretKey;

window.crypto.subtle.generateKey({
            name: &quot;AES-GCM&quot;,
            length: 256, //can be  128, 192, or 256
        },
        false, //whether the key is extractable (i.e. can be used in exportKey)
        [&quot;encrypt&quot;, &quot;decrypt&quot;] //can &quot;encrypt&quot;, &quot;decrypt&quot; or  &quot;wrapKey&quot;, or &quot;unwrapKey&quot;
    ).then(function(key) {
        secretKey = key;
    })
    .catch(function(err) {
        console.error(err);
    });


function AES256_GCM_ENCRYPT() {

    if (secretKey == null) {
        alert(&quot;Failed to Generate AES Keys Check The browser Comptabilty &quot;)
        return;
    }

    var plainText = document.getElementById(&quot;plainTextGCM&quot;).value;

    return crypto.subtle.encrypt({
        name: &quot;aes-gcm&quot;,
        iv: iv,
        tagLength: 128 //can be 32, 64, 96, 104, 112, 120 or 128 (default)
    }, secretKey, asciiToUint8Array(plainText)).then(function(cipherText) {
        document.getElementById(&quot;cipherTextGCM&quot;).value = bytesToHexString(cipherText);
    }, failAndLog);

}

function AES256_GCM_decrypt() {

    if (secretKey == null) {
        alert(&quot;Failed to Generate AES Keys Check The browser Comptabilty &quot;)
        return;
    }

    var cipherText = document.getElementById(&quot;cipherTextGCM&quot;).value;
    crypto.subtle.decrypt({
            name: &quot;aes-gcm&quot;,
            iv: iv,
            tagLength: 128 //can be 32, 64, 96, 104, 112, 120 or 128 (default)
        },
        secretKey,
        hexStringToUint8Array(cipherText)
    ).then(
        function(plainText) {
            document.getElementById(&quot;resultGCM&quot;).innerHTML = &quot;Result: &quot; + bytesToASCIIString(plainText);
        },
        function(result) {
            document.getElementById(&quot;resultGCM&quot;).innerHTML = &quot;Result: &quot; + result;
        });
}
</code></pre>
<p><strong>The HTML</strong></p>
<pre><code class="html"> &lt;div&gt;
    Plain Text: &lt;input type=&quot;text&quot; id=&quot;plainTextGCM&quot; value=&quot;Hello 8gwifi.org&quot;&gt;
    &lt;button type=&quot;button&quot; onclick=&quot;AES256_GCM_ENCRYPT()&quot;&gt;AES256-GCM-ENCRYPT&lt;/button&gt;
&lt;/div&gt;
&lt;div&gt;
    Cipher Text: &lt;input type=&quot;text&quot; id=&quot;cipherTextGCM&quot; size=&quot;50&quot;&gt;
    &lt;button type=&quot;button&quot; onclick=&quot;AES256_GCM_decrypt()&quot;&gt;AES256_GCM_decrypt&lt;/button&gt;
&lt;/div&gt;
&lt;div id=&quot;resultGCM&quot;&gt;
    Result:
&lt;/div&gt;
</code></pre>
<hr>
Download the sample code <a href="https://drive.google.com/file/d/146MLj4CMk_pC1ybq58S8SUDwUdIflK7y/view?usp=sharing">here </a>

<hr>
Next Reading <a href="window-crypto-aes.jsp">Perform AES Encryption Using importKey Method </a>

<%@ include file="thanks.jsp"%>

<hr>

<%@ include file="addcomments.jsp"%>
      <!-- Comments Form -->
    

          <!-- Single Comment -->
 

          <!-- Comment with nested comments -->
        
          

        </div>

		
        
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Ad Widget -->
         <%@ include file="footer_adsense.jsp"%> 
         
         <%@ include file="related-window-crypto.jsp"%>

		 <%@ include file="related-cryptography.jsp"%>
          <!-- Article Widget -->
         <%@ include file="related-ansible.jsp"%>
         
         <%@ include file="related-kube.jsp"%>
         
         
         
         <%@ include file="related-openstack.jsp"%>
         <%@ include file="related-linux.jsp"%>
         
         
         <!-- Topic Widget -->
         <%@ include file="side.jsp"%>
         
           <!-- Add Comments Support -->
         
         
         

        </div>


      </div>
      
      <!-- /.row -->


	
    
    </div>
    
    
    
    
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 8gwifi.org 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    
    Here

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


  </body>

</html>